# Introduction {#intro}

"Everybody should have the opportunity to find facts and break the myths with our statistics!" Statistics Sweden twitter account, sverigeisiffror.

Introduction  
Personal development in R, Statisics, Scientific Report, Markdown, and GitHub  
with data from Statistics Sweden. I will extract statistics from Statistics   
Sweden regarding the labour market, salaries and other relevant data from   
engineers, primarily in Jönköping county. 

About me
In 1999 I finished my Master in Computing Science education at Gothenburg University. In spring 2000 I moved to Jönköping and started to work as an embedded programmer at Saab Avionics. 
During the autumn that year I became a member of the local union. In 2001 I attended my first wage negotiation for The Swedish Association of Graduate Engineers at Saab Avionics. 
Since then I have been interested in the wage formation for engineers in Sweden and the Jönköping county.
In 2019 I am still employed at Saab Avionics, the chairman at The Swedish Association of Graduate Engineers at Saab Avionics, the chairman at The Swedish Association of Graduate Engineers at the Jönköpiong county and
a member of Jönköpingslistan, The Swedish Association of Graduate Engineers council.c

Wage statistics
The Mediation Institute is responsible for Sweden's official salary statistics. This applies to three types of statistics: cyclical wage statistics, wage structure statistics and statistics supplied to the European statistical body Eurostat.
The statistics are collected and processed by Statistics Sweden. It is reported both on Statistics Sweden's website and here on the Mediation Institute's website.

Economic Wage statistics
The cyclical wage statistics show wage developments month by month. It is the most up-to-date salary statistics since it is published two months after the survey. It is then revised when new information arrives and can be regarded as definitive one year after the measurement.

Structure of Earnings
Once a year, the salary structure statistics provide an overview and comparable statistics on the salary structure for the entire labour market.
The salary structure statistics give a picture of the wage situation in the various sectors of society, but also show the wages of 429 professions or professional groups.

The Confederation of Swedish Enterprise produces wage statistics on behalf of the member organizations. The wage statistics are used in negotiations with trade unions, in advising the companies and in the companies' analysis work.

The Confederation of Swedish Enterprise and Industry co-operates with Statistics Sweden, which is responsible for the official wage statistics in Sweden. The collaboration means that member companies do not have to report wage statistics to both Statistics Sweden and The Confederation of Swedish Enterprise. This minimizes corporate work.


SSYK (Standard for Swedish Occupational Classification) is a system for classifying individuals' occupation and work. 
It is based on the international professional standard ISCO-08 (International Standard Classification of Occupations) 
used in reporting and compiling statistics within the EU. SSYK is based on two main concepts, the type of work performed 
and the qualifications required. Qualifications mean the knowledge and skills required to perform the tasks that belong 
to a given job. It should be pointed out that it is the qualifications that the work in question requires that matter, 
not the qualifications that the worker possesses that constitute the work. The knowledge and skills required for the 
job may as well have been acquired through work experience as well as through formal education. If the degree of 
difficulty or orientation of the tasks varies, the worker shall be classified in the area in which the worker mainly works.

Occupation area 2 - The professions with requirements for in-depth higher education
The field of work includes: 
· developing theories, models and methods and designing their practical applications in physics, 
chemistry, mathematics, statistics, engineering, pharmacology, environment, agriculture and forestry, medicine, economics, 
finance, marketing and informatics, law, social sciences and humanities 
· draw buildings etc. and lead construction and civil engineering projects 
· plan and control extraction and manufacturing processes 
· design and develop products 
· verify compliance with health and environmental protection regulations 
· investigate and treat patients 
· teach and develop teaching methodology 
· organize activities at museums, libraries etc. and within care and social services 
· do financial investigations, plan and investigate the activities of companies and organizations 
· handle cases and prepare reports 
· analyze, design, develop, test, manage and manage IT systems 
· make reports, write articles or literary works, produce radio and television programs 
· create works of art, compose, interpret or make music, drama and dance 
· lead and plan assembly work. 

The occupation area comprises the following main groups: 
21 Professions with requirements for advanced university competence in science and technology 
22 Professions with requirements for advanced university competence in health care 
23 Professions with requirements for advanced university competence in education 
24 Profession with requirements for advanced proficiency in advanced education 
25 Professions with requirements for in-depth higher education in IT 
26 Professions with requirements for in-depth higher education in law, culture and social work, etc.

 
2141 The MSc in Logistics and Production Planning Develops, manages, plans and controls material and information flows and 
production planning. Manages manufacturing operations and assesses cost efficiency. Decides together with market organization 
and customer on schedule and production volume. Plans and decides on the supply and transport chain, as well as plant and system plans. 
2142 Civil Engineering in Construction and Engineering Develops construction methods, products, services and materials in 
construction engineering and road and water engineering. Leads and plans design and construction work and implementation of 
construction and civil engineering projects. Responsible for inspecting and inspecting construction, materials and more. 
Develops guidelines and methods for quality assurance. 2143 The MSc in electrical engineering Develops theories, models and 
methods in electrical engineering. Leads design and construction work relating to electrical engineering products and plants. 
Responsible for production and technological development, as well as for testing and testing of electrotechnical products and plants. 
Examines and advises on the technical aspects of electrical materials, products or processes. 2144 Civil Engineering in 
Mechanical Engineering Develops theories, models and methods in the manufacturing industry eg. machine and vehicle technology. 
Leads project, design and constructural work relating to vehicles, components, machines and other mechanical equipment, and heating, 
water, sanitation, ventilation and cooling systems. Responsible for inspection and checks. Develops guidelines and methods for 
quality assurance. 
2145 The MSc in Chemistry and Chemical Engineering Develops methods and products in chemistry, chemical engineering, 
food technology and more. Responsible for the production process and technological development in the manufacture of 
petroleum products, chemicals, chemical and chemical products, pharmaceuticals, synthetic materials or food. Responsible 
for quality, release and final control of chemical engineering products. 
2146 The MSc in Mining Engineering and Metallurgy Develops methods and products in Mining Engineering and Metallurgy. 
Responsible for production and technological development in the extraction of metals, oil and gas or in the manufacture 
of metals, alloys and metallurgical products. Responsible for quality and product controls. 
2149 Other Civil Engineering Professionals Perform other specialist work than within 
2141-2146. Examples of tasks: Develops methods and products and is responsible for production and technological 
development in the manufacture of metal, glass, ceramics, paper, leather, textile and wood products. 
Responsible for quality and product controls.