# Percent women in the countys  

214 Engineering professionals  
  
Percent women in the countys  
214 Engineering professionals  
Joint-stock corporations not controlled by the government sector  
  
```{r womencountys, echo = TRUE}  
options(tibble.print_max = Inf)
	 	 
readfile ("000000NL_3.csv") %>%   
  group_by (`region`, year) %>%   
  summarise (perc_women = perc_women (salary)) %>%  
  arrange (desc (perc_women)) %>%
  knitr::kable( 
  booktabs = TRUE,
  caption = 'Percent women in the countys')   
```  
  
```{r womencountys2, echo = TRUE, fig.cap = 'Percent women in the countys'}    
readfile ("000000NL_3.csv") %>%   
  group_by (`region`, year) %>%   
  summarise (perc_women = perc_women (salary)) %>%
  mutate(perc_women_n = as.numeric(sub("%", "", perc_women))) %>%
  mutate(lnkod_n = as.numeric(substr(region, 1,2))) %>%
  right_join(map_ln_n, by = "lnkod_n") %>%
  ggplot() +
    geom_polygon(mapping = aes(x = ggplot_long, y = ggplot_lat, group = lnkod, fill = perc_women_n)) +
    coord_equal()
``` 	
      
```{r womencountys3, echo = TRUE}  	  
readfile ("000000RM.csv") %>%   
  group_by (`region`, year) %>%   
  summarise (perc_women = perc_women (salary)) %>%	  
  arrange (desc (perc_women)) %>%
  knitr::kable(  
  booktabs = TRUE,
  caption = 'Percent women in the countys, Joint-stock corporations not controlled by the government sector')
```   
  
```{r womencountys4, echo = TRUE, fig.cap = 'Percent women in the countys, Joint-stock corporations not controlled by the government sector'}      
readfile ("000000RM.csv") %>%   
  group_by (`region`, year) %>%   
  summarise (perc_women = perc_women (salary)) %>%
  mutate(perc_women_n = as.numeric(sub("%", "", perc_women))) %>%
  mutate(lnkod_n = as.numeric(substr(region, 1,2))) %>%
  right_join(map_ln_n, by = "lnkod_n") %>%
  ggplot() +
    geom_polygon(mapping = aes(x = ggplot_long, y = ggplot_lat, group = lnkod, fill = perc_women_n)) +
    coord_equal()   
``` 
