# Civilingenjörsutbildning SUN 2000

Genomsnittlig grund- och månadslön samt kvinnors lön i procent av mäns lön  
efter utbildningsgrupp SUN 2000 och kön. År 2004 - 2017	  
Månadslön  
Kön=Totalt  
Only available at the Swedish SCB site  
    
```{r civingsalary, echo = TRUE, fig.cap = 'Månadslön Civilingenjörsutbildning'}  
readfile ("AM0110D2.csv") %>%   
  ggplot () +  
    geom_line (mapping = aes (x = year2, y = salary, colour = `utbildningsgrupp SUN 2000`)) +  
    theme (legend.position = "bottom") + 	  
	guides(col = guide_legend(title.position = "top", nrow = 5))   
```

Befolkningen 2006-2018 fördelad efter utbildningsgrupp (SUN 2000) och kön. 25-64 år	
Only available at the Swedish SCB site  

```{r civingant, echo = TRUE, fig.cap = 'Antal med Civilingenjörsutbildning'} 
readfile("tab8_tidsserie_2018.csv") %>%
  filter(`Utbildningsgrupp (SUN 2000)` == "Teknik och tillverkning") %>%
  filter(grepl("Civilingenjörsutbildning", `SUN 2000`)) %>%
  filter(grepl("Samtliga", year)) %>%
  ggplot () +  
    geom_line (mapping = aes (x = year2, y = salary, colour = `SUN 2000`)) +  
    theme (legend.position = "bottom") + 	  
	guides(col = guide_legend(title.position = "top", nrow = 5)) +
    scale_y_continuous(name = "Antal")    
```