<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 R&amp;D expenditures | SCB Engineers Jonkoping</title>
  <meta name="description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 R&amp;D expenditures | SCB Engineers Jonkoping" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  <meta name="github-repo" content="MikaelLundqvist/SCB-Engineers-Jonkoping" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 R&amp;D expenditures | SCB Engineers Jonkoping" />
  
  <meta name="twitter:description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  

<meta name="author" content="Mikael Lundqvist" />


<meta name="date" content="2019-10-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html">
<link rel="next" href="appendix-a.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SCB Engineers Jonkoping</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="help-functions.html"><a href="help-functions.html"><i class="fa fa-check"></i><b>3</b> Help functions</a></li>
<li class="chapter" data-level="4" data-path="natural-sciences.html"><a href="natural-sciences.html"><i class="fa fa-check"></i><b>4</b> Natural sciences</a></li>
<li class="chapter" data-level="5" data-path="number-of-physical-and-engineering-science-technicians-in-jonkoping-county.html"><a href="number-of-physical-and-engineering-science-technicians-in-jonkoping-county.html"><i class="fa fa-check"></i><b>5</b> Number of Physical and engineering science technicians in Jönköping county</a></li>
<li class="chapter" data-level="6" data-path="percent-women-in-the-countys.html"><a href="percent-women-in-the-countys.html"><i class="fa fa-check"></i><b>6</b> Percent women in the countys</a></li>
<li class="chapter" data-level="7" data-path="engineering-professionals.html"><a href="engineering-professionals.html"><i class="fa fa-check"></i><b>7</b> Engineering professionals</a></li>
<li class="chapter" data-level="8" data-path="civilingenjorsutbildning-sun-2000.html"><a href="civilingenjorsutbildning-sun-2000.html"><i class="fa fa-check"></i><b>8</b> Civilingenjörsutbildning SUN 2000</a></li>
<li class="chapter" data-level="9" data-path="ssyk-214.html"><a href="ssyk-214.html"><i class="fa fa-check"></i><b>9</b> SSYK 214</a><ul>
<li class="chapter" data-level="9.1" data-path="ssyk-214.html"><a href="ssyk-214.html#average-monthly-salary-sek-by-region"><i class="fa fa-check"></i><b>9.1</b> Average monthly salary, SEK by region</a></li>
<li class="chapter" data-level="9.2" data-path="ssyk-214.html"><a href="ssyk-214.html#number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2014---2018"><i class="fa fa-check"></i><b>9.2</b> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.3" data-path="ssyk-214.html"><a href="ssyk-214.html#number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2003---2013"><i class="fa fa-check"></i><b>9.3</b> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.4" data-path="ssyk-214.html"><a href="ssyk-214.html#age-distribution-in-the-different-countys"><i class="fa fa-check"></i><b>9.4</b> Age distribution in the different countys</a></li>
<li class="chapter" data-level="9.5" data-path="ssyk-214.html"><a href="ssyk-214.html#sector-distribution-in-the-different-countys"><i class="fa fa-check"></i><b>9.5</b> Sector distribution in the different countys</a></li>
<li class="chapter" data-level="9.6" data-path="ssyk-214.html"><a href="ssyk-214.html#education-distribution-for-engineers"><i class="fa fa-check"></i><b>9.6</b> Education distribution for engineers</a></li>
<li class="chapter" data-level="9.7" data-path="ssyk-214.html"><a href="ssyk-214.html#average-monthly-pay-increase-by-occuption-year-2000---2013"><i class="fa fa-check"></i><b>9.7</b> Average monthly pay increase by occuption year 2000 - 2013</a></li>
<li class="chapter" data-level="9.8" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-year-2000---2013"><i class="fa fa-check"></i><b>9.8</b> SSYK 214, Architects, engineers and related professionals, Year 2000 - 2013</a></li>
<li class="chapter" data-level="9.9" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-year-2014---2018"><i class="fa fa-check"></i><b>9.9</b> SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.10" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-by-region-year-2000---2018"><i class="fa fa-check"></i><b>9.10</b> SSYK 214, Architects, engineers and related professionals by region, Year 2000 - 2018</a></li>
<li class="chapter" data-level="9.11" data-path="ssyk-214.html"><a href="ssyk-214.html#level-of-education-ssyk-214-architects-engineers-and-related-professionals"><i class="fa fa-check"></i><b>9.11</b> Level of education , SSYK 214, Architects, engineers and related professionals</a></li>
<li class="chapter" data-level="9.12" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018"><i class="fa fa-check"></i><b>9.12</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.13" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2003---2013"><i class="fa fa-check"></i><b>9.13</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.14" data-path="ssyk-214.html"><a href="ssyk-214.html#f-value-for-age-compared-to-yearly-increase-in-salary-cleaned-for-the-effect-of-age-year-2004---2013"><i class="fa fa-check"></i><b>9.14</b> F-value for age compared to yearly increase in salary cleaned for the effect of age, Year 2004 - 2013</a></li>
<li class="chapter" data-level="9.15" data-path="ssyk-214.html"><a href="ssyk-214.html#f-value-for-age-compared-to-yearly-increase-in-salary-cleaned-for-the-effect-of-age-year-2014---2018"><i class="fa fa-check"></i><b>9.15</b> F-value for age compared to yearly increase in salary cleaned for the effect of age, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.16" data-path="ssyk-214.html"><a href="ssyk-214.html#womens-urbanization-comparison-between-the-ssyk-population-dependence-year-2003---2013"><i class="fa fa-check"></i><b>9.16</b> Women’s urbanization, comparison between the SSYK, population dependence, Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.17" data-path="ssyk-214.html"><a href="ssyk-214.html#womens-urbanization-comparison-between-the-ssyk-population-dependence-year-2014---2018"><i class="fa fa-check"></i><b>9.17</b> Women’s urbanization, comparison between the SSYK, population dependence, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.18" data-path="ssyk-214.html"><a href="ssyk-214.html#womens-urbanization-comparison-between-the-ssyk-salary-dependence-year-2003---2013"><i class="fa fa-check"></i><b>9.18</b> Women’s urbanization, comparison between the SSYK, salary dependence, Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.19" data-path="ssyk-214.html"><a href="ssyk-214.html#womens-urbanization-comparison-between-the-ssyk-salary-dependence-year-2014---2018"><i class="fa fa-check"></i><b>9.19</b> Women’s urbanization, comparison between the SSYK, salary dependence, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.20" data-path="ssyk-214.html"><a href="ssyk-214.html#salary-correlation-with-population-in-region-comparison-between-the-ssyk-year-2003---2013"><i class="fa fa-check"></i><b>9.20</b> Salary correlation with population in region, comparison between the SSYK, Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.21" data-path="ssyk-214.html"><a href="ssyk-214.html#salary-correlation-with-population-in-region-comparison-between-the-ssyk-year-2014---2018"><i class="fa fa-check"></i><b>9.21</b> Salary correlation with population in region, comparison between the SSYK, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.22" data-path="ssyk-214.html"><a href="ssyk-214.html#women-with-higher-paid-jobs-migrate-to-regions-with-higher-salaries-women-with-lower-paid-jobs-migrate-to-regions-with-lower-salaries-year-2004---2013"><i class="fa fa-check"></i><b>9.22</b> Women with higher paid jobs migrate to regions with higher salaries, women with lower paid jobs migrate to regions with lower salaries, Year 2004 - 2013</a></li>
<li class="chapter" data-level="9.23" data-path="ssyk-214.html"><a href="ssyk-214.html#women-with-higher-paid-jobs-migrate-to-regions-with-higher-salaries-women-with-lower-paid-jobs-migrate-to-regions-with-lower-salaries-year-2014---2018"><i class="fa fa-check"></i><b>9.23</b> Women with higher paid jobs migrate to regions with higher salaries, women with lower paid jobs migrate to regions with lower salaries, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.24" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-salary-level-and-the-f-value-for-age-year-2004---2013"><i class="fa fa-check"></i><b>9.24</b> The correlation between salary level and the F-value for age, Year 2004 - 2013</a></li>
<li class="chapter" data-level="9.25" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-salary-level-and-the-f-value-for-age-year-2014---2018"><i class="fa fa-check"></i><b>9.25</b> The correlation between salary level and the F-value for age, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.26" data-path="ssyk-214.html"><a href="ssyk-214.html#animations-ssyk-214-architects-engineers-and-related-professionals"><i class="fa fa-check"></i><b>9.26</b> Animations , SSYK 214, Architects, engineers and related professionals</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ssyk-311.html"><a href="ssyk-311.html"><i class="fa fa-check"></i><b>10</b> SSYK 311</a><ul>
<li class="chapter" data-level="10.1" data-path="ssyk-311.html"><a href="ssyk-311.html#average-monthly-salary-sek-by-region-1"><i class="fa fa-check"></i><b>10.1</b> Average monthly salary, SEK by region</a></li>
<li class="chapter" data-level="10.2" data-path="ssyk-311.html"><a href="ssyk-311.html#number-of-men-and-women-in-ssyk-311-and-the-percentage-of-women-in-ssyk-311-year-2014---2018"><i class="fa fa-check"></i><b>10.2</b> Number of men and women in SSYK 311 and the percentage of women in SSYK 311 Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.3" data-path="ssyk-311.html"><a href="ssyk-311.html#number-of-men-and-women-in-ssyk-311-and-the-percentage-of-women-in-ssyk-311-year-2003---2013"><i class="fa fa-check"></i><b>10.3</b> Number of men and women in SSYK 311 and the percentage of women in SSYK 311 Year 2003 - 2013</a></li>
<li class="chapter" data-level="10.4" data-path="ssyk-311.html"><a href="ssyk-311.html#age-distribution-in-the-different-countys-1"><i class="fa fa-check"></i><b>10.4</b> Age distribution in the different countys</a></li>
<li class="chapter" data-level="10.5" data-path="ssyk-311.html"><a href="ssyk-311.html#sector-distribution-in-the-different-countys-1"><i class="fa fa-check"></i><b>10.5</b> Sector distribution in the different countys</a></li>
<li class="chapter" data-level="10.6" data-path="ssyk-311.html"><a href="ssyk-311.html#education-distribution-for-engineers-1"><i class="fa fa-check"></i><b>10.6</b> Education distribution for engineers</a></li>
<li class="chapter" data-level="10.7" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-year-2000---2013"><i class="fa fa-check"></i><b>10.7</b> SSYK 311, Physical and engineering science technicians, Year 2000 - 2013</a></li>
<li class="chapter" data-level="10.8" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-year-2014---2018"><i class="fa fa-check"></i><b>10.8</b> SSYK 311, Physical and engineering science technicians, Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.9" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-by-region-year-2000---2018"><i class="fa fa-check"></i><b>10.9</b> SSYK 311, Physical and engineering science technicians by region, Year 2000 - 2018</a></li>
<li class="chapter" data-level="10.10" data-path="ssyk-311.html"><a href="ssyk-311.html#level-of-education-ssyk-311-physical-and-engineering-science-technicians"><i class="fa fa-check"></i><b>10.10</b> Level of education , SSYK 311, Physical and engineering science technicians</a></li>
<li class="chapter" data-level="10.11" data-path="ssyk-311.html"><a href="ssyk-311.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018-1"><i class="fa fa-check"></i><b>10.11</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.12" data-path="ssyk-311.html"><a href="ssyk-311.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2003---2013-1"><i class="fa fa-check"></i><b>10.12</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2003 - 2013</a></li>
<li class="chapter" data-level="10.13" data-path="ssyk-311.html"><a href="ssyk-311.html#animations-ssyk-214-architects-engineers-and-related-professionals-1"><i class="fa fa-check"></i><b>10.13</b> Animations , SSYK 214, Architects, engineers and related professionals</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="average-monthly-pay-year-1991-2015.html"><a href="average-monthly-pay-year-1991-2015.html"><i class="fa fa-check"></i><b>11</b> Average monthly pay Year 1991 - 2015</a></li>
<li class="chapter" data-level="12" data-path="utbildningsniva.html"><a href="utbildningsniva.html"><i class="fa fa-check"></i><b>12</b> Utbildningsnivå</a><ul>
<li class="chapter" data-level="12.1" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-region.-year-2014---2018"><i class="fa fa-check"></i><b>12.1</b> The correlation between the proportion of engineers who are women and the number of the population who have 3 years or more post-secondary education in the region. Year 2014 - 2018</a></li>
<li class="chapter" data-level="12.2" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-number-of-engineers-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-regions-year-2014---2018."><i class="fa fa-check"></i><b>12.2</b> The correlation between the number of engineers and the number of the population who have 3 years or more post-secondary education in the regions, Year 2014 - 2018.</a></li>
<li class="chapter" data-level="12.3" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-number-of-engineers-and-the-proportion-of-engineers-who-are-women-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>12.3</b> The correlation between the number of engineers and the proportion of engineers who are women in the regions, Year 2014 - 2018</a></li>
<li class="chapter" data-level="12.4" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-salary-of-engineers-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>12.4</b> The correlation between the salary of engineers and the number of the population who have 3 years or more post-secondary education in the regions, Year 2014 - 2018</a></li>
<li class="chapter" data-level="12.5" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-proportion-of-the-population-who-have-3-years-or-more-post-secondary-education-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>12.5</b> The correlation between the proportion of the population who have 3 years or more post-secondary education and the number of the population who have 3 years or more post-secondary education in the regions, Year 2014 - 2018</a></li>
<li class="chapter" data-level="12.6" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-region.-year-2003---2013"><i class="fa fa-check"></i><b>12.6</b> The correlation between the proportion of engineers who are women and the number of the population who have 3 years or more post-secondary education in the region. Year 2003 - 2013</a></li>
<li class="chapter" data-level="12.7" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-number-of-engineers-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-regions-year-2003---2013."><i class="fa fa-check"></i><b>12.7</b> The correlation between the number of engineers and the number of the population who have 3 years or more post-secondary education in the regions, Year 2003 - 2013.</a></li>
<li class="chapter" data-level="12.8" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-number-of-engineers-and-the-proportion-of-engineers-who-are-women-in-the-regions-year-2003---2013"><i class="fa fa-check"></i><b>12.8</b> The correlation between the number of engineers and the proportion of engineers who are women in the regions, Year 2003 - 2013</a></li>
<li class="chapter" data-level="12.9" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-salary-of-engineers-and-the-number-of-the-population-who-have-3-years-or-more-post-secondary-education-in-the-regions-year-2003---2013"><i class="fa fa-check"></i><b>12.9</b> The correlation between the salary of engineers and the number of the population who have 3 years or more post-secondary education in the regions, Year 2003 - 2013</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><i class="fa fa-check"></i><b>13</b> The correlation between the proportion of Physical and engineering science technicians who are women and the number of the population in the region. Year 2014 - 2018</a><ul>
<li class="chapter" data-level="13.1" data-path="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html#the-correlation-between-the-number-of-physical-and-engineering-science-technicians-and-the-number-of-the-population-in-the-regions-year-2014---2018."><i class="fa fa-check"></i><b>13.1</b> The correlation between the number of Physical and engineering science technicians and the number of the population in the regions, Year 2014 - 2018.</a></li>
<li class="chapter" data-level="13.2" data-path="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html#the-correlation-between-the-number-of-physical-and-engineering-science-technicians-and-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>13.2</b> The correlation between the number of Physical and engineering science technicians and the proportion of Physical and engineering science technicians who are women in the regions, Year 2014 - 2018</a></li>
<li class="chapter" data-level="13.3" data-path="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html#the-correlation-between-the-salary-of-physical-and-engineering-science-technicians-and-the-number-of-the-population-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>13.3</b> The correlation between the salary of Physical and engineering science technicians and the number of the population in the regions, Year 2014 - 2018</a></li>
<li class="chapter" data-level="13.4" data-path="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html"><a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html#the-correlation-between-the-salary-of-physical-and-engineering-science-technicians-and-the-number-of-physical-and-engineering-science-technicians-in-the-regions-year-2014---2018"><i class="fa fa-check"></i><b>13.4</b> The correlation between the salary of Physical and engineering science technicians and the number of Physical and engineering science technicians in the regions, Year 2014 - 2018</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="rd-expenditures.html"><a href="rd-expenditures.html"><i class="fa fa-check"></i><b>14</b> R&amp;D expenditures</a><ul>
<li class="chapter" data-level="14.1" data-path="rd-expenditures.html"><a href="rd-expenditures.html#correlation-between-rd-person-years-performed-by-employees-of-a-higher-education-institution-by-region-and-per-cent-of-engineers-who-are-women"><i class="fa fa-check"></i><b>14.1</b> Correlation between R&amp;D person years performed by employees of a higher education institution by region and per cent of engineers who are women</a></li>
<li class="chapter" data-level="14.2" data-path="rd-expenditures.html"><a href="rd-expenditures.html#correlation-between-total-rd-person-years-performed-by-employees-of-a-higher-education-institution-by-region-and-number-of-the-population-who-are-engineers"><i class="fa fa-check"></i><b>14.2</b> Correlation between total R&amp;D person years performed by employees of a higher education institution by region and number of the population who are engineers</a></li>
<li class="chapter" data-level="14.3" data-path="rd-expenditures.html"><a href="rd-expenditures.html#correlation-between-regional-distribution-of-enterprises-rd-and-number-of-the-population-who-are-engineers"><i class="fa fa-check"></i><b>14.3</b> Correlation between regional distribution of enterprises R&amp;D and number of the population who are engineers</a></li>
<li class="chapter" data-level="14.4" data-path="rd-expenditures.html"><a href="rd-expenditures.html#f-value-for-regional-distribution-of-enterprises-rd-compared-to-the-level-of-regional-distribution-of-enterprises-rd"><i class="fa fa-check"></i><b>14.4</b> F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="appendix-a.html"><a href="appendix-a.html"><i class="fa fa-check"></i><b>15</b> Appendix A</a></li>
<li class="chapter" data-level="16" data-path="appendix-b.html"><a href="appendix-b.html"><i class="fa fa-check"></i><b>16</b> Appendix B</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/MikaelLundqvist/SCB-Engineers-Jonkoping" target="blank">Github</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SCB Engineers Jonkoping</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rd-expenditures" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> R&amp;D expenditures</h1>
<p>Employees 16-64 years by region of work, occupation (3-digit SSYK 2012) and sex. Year 2014 - 2017
214 Engineering professionals</p>
<p>Population 16-74 years of age by region, highest level of education, age and sex. Year 1985 - 2018
total, 16-74 years</p>
<p>Regional distribution of enterprises R&amp;D. Every other year 2007 - 2017
Intramural R&amp;D, SEK million</p>
<p>Total R&amp;D person years performed by employees of a higher education institution by region, sex and field of science. Every second year 2013 - 2017
Total R&amp;D person years
County
men, women
All fields of science and technology</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb265-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb265-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb265-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb265-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb265-18" title="18">  </a>
<a class="sourceLine" id="cb265-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb265-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb265-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb265-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb265-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb265-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb265-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb265-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb265-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb265-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb265-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb265-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb265-31" title="31"></a>
<a class="sourceLine" id="cb265-32" title="32"><span class="kw">chart.Correlation</span>(tb1, <span class="dt">histogram=</span><span class="ot">TRUE</span>, <span class="dt">pch=</span><span class="dv">19</span>)</a></code></pre></div>
<div class="figure"><span id="fig:rndexpenditures1"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures1-1.png" alt="Correlation matrix between R&amp;D expenditures, number of engineers and level of education" width="672" />
<p class="caption">
Figure 14.1: Correlation matrix between R&amp;D expenditures, number of engineers and level of education
</p>
</div>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb266-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb266-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb266-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb266-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb266-18" title="18">  </a>
<a class="sourceLine" id="cb266-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb266-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb266-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb266-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb266-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb266-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb266-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb266-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb266-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb266-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb266-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb266-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb266-31" title="31">  </a>
<a class="sourceLine" id="cb266-32" title="32"><span class="kw">get_clust_tendency</span>(</a>
<a class="sourceLine" id="cb266-33" title="33">  tb1, </a>
<a class="sourceLine" id="cb266-34" title="34">  <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb266-35" title="35">  <span class="dt">gradient =</span> <span class="kw">list</span>(<span class="dt">low =</span> <span class="st">&quot;steelblue&quot;</span>,  <span class="dt">high =</span> <span class="st">&quot;white&quot;</span>))  </a></code></pre></div>
<pre><code>## $hopkins_stat
## [1] 0.04789467
## 
## $plot</code></pre>
<div class="figure"><span id="fig:rndexpenditures2"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures2-1.png" alt="Clustering tendancy for data" width="672" />
<p class="caption">
Figure 14.2: Clustering tendancy for data
</p>
</div>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb268-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb268-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb268-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb268-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb268-18" title="18">  </a>
<a class="sourceLine" id="cb268-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb268-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb268-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb268-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb268-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb268-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb268-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb268-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb268-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb268-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb268-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb268-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb268-31" title="31">  </a>
<a class="sourceLine" id="cb268-32" title="32">tb2 &lt;-<span class="st"> </span>tb1 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">scale</span>()  </a>
<a class="sourceLine" id="cb268-33" title="33">  </a>
<a class="sourceLine" id="cb268-34" title="34">intern &lt;-<span class="st"> </span><span class="kw">clValid</span>(tb2, <span class="dt">nClust =</span> <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>, </a>
<a class="sourceLine" id="cb268-35" title="35">              <span class="dt">clMethods =</span> <span class="kw">c</span>(<span class="st">&quot;hierarchical&quot;</span>,<span class="st">&quot;kmeans&quot;</span>,<span class="st">&quot;pam&quot;</span>),</a>
<a class="sourceLine" id="cb268-36" title="36">              <span class="dt">validation =</span> <span class="st">&quot;internal&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in clValid(tb2, nClust = 2:6, clMethods = c(&quot;hierarchical&quot;,
## &quot;kmeans&quot;, : rownames for data not specified, using 1:nrow(data)</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1"><span class="kw">summary</span>(intern) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb270-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb270-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb270-4" title="4">    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb270-5" title="5">    <span class="dt">caption =</span> <span class="st">&#39;Clustering validation measures&#39;</span>)           </a></code></pre></div>
<pre><code>## 
## Clustering Methods:
##  hierarchical kmeans pam 
## 
## Cluster sizes:
##  2 3 4 5 6 
## 
## Validation Measures:
##                                  2       3       4       5       6
##                                                                   
## hierarchical Connectivity   5.6464 10.0151 13.9048 20.1786 22.8548
##              Dunn           0.4585  0.5304  0.5388  0.4915  0.4915
##              Silhouette     0.6346  0.5555  0.3919  0.4039  0.4050
## kmeans       Connectivity   5.6464 10.1651 18.7151 20.1786 22.8548
##              Dunn           0.4585  0.5385  0.4235  0.4915  0.4915
##              Silhouette     0.6346  0.4999  0.4037  0.4039  0.4050
## pam          Connectivity   5.6464 16.8294 23.2329 33.0845 36.8401
##              Dunn           0.4585  0.2863  0.1590  0.1590  0.1579
##              Silhouette     0.6346  0.2690  0.2254  0.2326  0.2533
## 
## Optimal Scores:
## 
##              Score  Method       Clusters
## Connectivity 5.6464 hierarchical 2       
## Dunn         0.5388 hierarchical 4       
## Silhouette   0.6346 hierarchical 2</code></pre>
<pre><code>## Warning in kable_markdown(x, padding = padding, ...): The table should have
## a header (column names)</code></pre>
<p>Table: (#tab:rndexpenditures3)Clustering validation measures</p>
<p>||
||
||
||</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb273-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb273-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb273-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb273-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb273-18" title="18">  </a>
<a class="sourceLine" id="cb273-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb273-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb273-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb273-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb273-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb273-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb273-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb273-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb273-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb273-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb273-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb273-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb273-31" title="31">  </a>
<a class="sourceLine" id="cb273-32" title="32">tb2 &lt;-<span class="st"> </span>tb1 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">scale</span>()  </a>
<a class="sourceLine" id="cb273-33" title="33">  </a>
<a class="sourceLine" id="cb273-34" title="34">d &lt;-<span class="st"> </span><span class="kw">dist</span>(tb2, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>)</a>
<a class="sourceLine" id="cb273-35" title="35"></a>
<a class="sourceLine" id="cb273-36" title="36">res.hc &lt;-<span class="st"> </span><span class="kw">hclust</span>(d, <span class="dt">method =</span> <span class="st">&quot;ward.D2&quot;</span> )</a>
<a class="sourceLine" id="cb273-37" title="37"></a>
<a class="sourceLine" id="cb273-38" title="38">grp &lt;-<span class="st"> </span><span class="kw">cutree</span>(res.hc, <span class="dt">k =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb273-39" title="39"></a>
<a class="sourceLine" id="cb273-40" title="40"><span class="kw">plot</span>(res.hc, <span class="dt">cex =</span> <span class="fl">0.6</span>) <span class="co"># plot tree</span></a>
<a class="sourceLine" id="cb273-41" title="41"><span class="kw">rect.hclust</span>(res.hc, <span class="dt">k =</span> <span class="dv">2</span>, <span class="dt">border =</span> <span class="dv">2</span><span class="op">:</span><span class="dv">5</span>)</a></code></pre></div>
<div class="figure"><span id="fig:rndexpenditures4"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures4-1.png" alt="Hierarchical clustering using Ward's method" width="672" />
<p class="caption">
Figure 14.3: Hierarchical clustering using Ward’s method
</p>
</div>
<div id="correlation-between-rd-person-years-performed-by-employees-of-a-higher-education-institution-by-region-and-per-cent-of-engineers-who-are-women" class="section level2">
<h2><span class="header-section-number">14.1</span> Correlation between R&amp;D person years performed by employees of a higher education institution by region and per cent of engineers who are women</h2>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb274-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb274-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb274-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb274-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb274-18" title="18">  </a>
<a class="sourceLine" id="cb274-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb274-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb274-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb274-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb274-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb274-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb274-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb274-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb274-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb274-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb274-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb274-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb274-31" title="31">  </a>
<a class="sourceLine" id="cb274-32" title="32">tb2 &lt;-<span class="st"> </span>tb1</a>
<a class="sourceLine" id="cb274-33" title="33"></a>
<a class="sourceLine" id="cb274-34" title="34">tb3 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">scale</span>()  </a>
<a class="sourceLine" id="cb274-35" title="35">  </a>
<a class="sourceLine" id="cb274-36" title="36">d &lt;-<span class="st"> </span><span class="kw">dist</span>(tb3, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>)</a>
<a class="sourceLine" id="cb274-37" title="37"></a>
<a class="sourceLine" id="cb274-38" title="38">res.hc &lt;-<span class="st"> </span><span class="kw">hclust</span>(d, <span class="dt">method =</span> <span class="st">&quot;ward.D2&quot;</span> )</a>
<a class="sourceLine" id="cb274-39" title="39"></a>
<a class="sourceLine" id="cb274-40" title="40">grp &lt;-<span class="st"> </span><span class="kw">cutree</span>(res.hc, <span class="dt">k =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb274-41" title="41"></a>
<a class="sourceLine" id="cb274-42" title="42">tb4 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp)</a>
<a class="sourceLine" id="cb274-43" title="43"></a>
<a class="sourceLine" id="cb274-44" title="44">model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(perc_women <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb274-45" title="45"></a>
<a class="sourceLine" id="cb274-46" title="46"><span class="kw">summary</span>(model1) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb274-47" title="47"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-48" title="48"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb274-49" title="49">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb274-50" title="50">  <span class="dt">caption =</span> <span class="st">&#39;Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures5">Table 14.2: </span>Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-3232.4031087</td>
<td align="right">0</td>
<td align="right">-3.956486e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">0.0058631</td>
<td align="right">0</td>
<td align="right">2.877303e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">-0.0001395</td>
<td align="right">0</td>
<td align="right">-2.654362e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">0.0000000</td>
<td align="right">0</td>
<td align="right">8.429982e-01</td>
<td align="right">0.4611338</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">1.6116179</td>
<td align="right">0</td>
<td align="right">3.981184e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">0.0000000</td>
<td align="right">0</td>
<td align="right">-1.035823e+00</td>
<td align="right">0.3764532</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">-0.0000488</td>
<td align="right">0</td>
<td align="right">-1.887907e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">0.0000000</td>
<td align="right">0</td>
<td align="right">1.588736e-01</td>
<td align="right">0.8838614</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">0.0001593</td>
<td align="right">0</td>
<td align="right">1.705022e+12</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" title="1">model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(perc_women <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb275-2" title="2"></a>
<a class="sourceLine" id="cb275-3" title="3"><span class="kw">summary</span>(model2) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb275-4" title="4"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb275-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb275-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb275-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Women engineers and population with 3 years or more post-secondary education&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures5">Table 14.2: </span>Women engineers and population with 3 years or more post-secondary education</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-405.3202427</td>
<td align="right">834.1392847</td>
<td align="right">-0.4859143</td>
<td align="right">0.6288587</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">0.0033701</td>
<td align="right">0.0011007</td>
<td align="right">3.0617573</td>
<td align="right">0.0033322</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">-0.0002970</td>
<td align="right">0.0007141</td>
<td align="right">-0.4159109</td>
<td align="right">0.6790101</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">-0.0002938</td>
<td align="right">0.0003383</td>
<td align="right">-0.8686163</td>
<td align="right">0.3886372</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">0.2109100</td>
<td align="right">0.4144858</td>
<td align="right">0.5088473</td>
<td align="right">0.6127896</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">25.8430631</td>
<td align="right">25.0172384</td>
<td align="right">1.0330102</td>
<td align="right">0.3058874</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">0.0000128</td>
<td align="right">0.0001935</td>
<td align="right">0.0661902</td>
<td align="right">0.9474541</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">-0.0001661</td>
<td align="right">0.0011022</td>
<td align="right">-0.1506891</td>
<td align="right">0.8807438</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">0.0021199</td>
<td align="right">0.0017251</td>
<td align="right">1.2288449</td>
<td align="right">0.2240926</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">-93.1069852</td>
<td align="right">49.9236663</td>
<td align="right">-1.8649869</td>
<td align="right">0.0672449</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" title="1"><span class="kw">Anova</span>(model2, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb276-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb276-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb276-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb276-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<pre><code>## Note: model has aliased coefficients
##       sums of squares computed by model comparison</code></pre>
<table>
<caption><span id="tab:rndexpenditures5">Table 14.2: </span>Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">salary.x.x</td>
<td align="right">95.2758135</td>
<td align="right">1</td>
<td align="right">9.3743575</td>
<td align="right">0.0033322</td>
</tr>
<tr class="even">
<td align="left">salary.y</td>
<td align="right">1.7580924</td>
<td align="right">1</td>
<td align="right">0.1729819</td>
<td align="right">0.6790101</td>
</tr>
<tr class="odd">
<td align="left">salary.x</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">year2.x</td>
<td align="right">2.6315775</td>
<td align="right">1</td>
<td align="right">0.2589256</td>
<td align="right">0.6127896</td>
</tr>
<tr class="odd">
<td align="left">utbregno</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">10.8455204</td>
<td align="right">1</td>
<td align="right">1.0671101</td>
<td align="right">0.3058874</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">0.0445275</td>
<td align="right">1</td>
<td align="right">0.0043811</td>
<td align="right">0.9474541</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">0.2307836</td>
<td align="right">1</td>
<td align="right">0.0227072</td>
<td align="right">0.8807438</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">15.3474169</td>
<td align="right">1</td>
<td align="right">1.5100598</td>
<td align="right">0.2240926</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">35.3502704</td>
<td align="right">1</td>
<td align="right">3.4781762</td>
<td align="right">0.0672449</td>
</tr>
<tr class="odd">
<td align="left">grp</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">589.4801006</td>
<td align="right">58</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" title="1">tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb278-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> salary.x.x, <span class="dt">y =</span> perc_women, <span class="dt">colour =</span> region, <span class="dt">size =</span> year2.x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb278-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb278-4" title="4"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb278-5" title="5"><span class="st">  </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>grp) <span class="op">+</span></a>
<a class="sourceLine" id="cb278-6" title="6"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb278-7" title="7">    <span class="dt">x =</span> <span class="st">&quot;Total R&amp;D person years performed by employees of a higher education institution by region&quot;</span>,</a>
<a class="sourceLine" id="cb278-8" title="8">    <span class="dt">y =</span> <span class="st">&quot;Per cent of engineers who are women&quot;</span></a>
<a class="sourceLine" id="cb278-9" title="9">  )</a></code></pre></div>
<pre><code>## Warning: Removed 92 rows containing missing values (geom_point).</code></pre>
<div class="figure"><span id="fig:rndexpenditures5"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures5-1.png" alt="Correlation between R&amp;D person years performed by employees of a higher education institution by region and per cent of engineers who are women" width="672" />
<p class="caption">
Figure 14.4: Correlation between R&amp;D person years performed by employees of a higher education institution by region and per cent of engineers who are women
</p>
</div>
</div>
<div id="correlation-between-total-rd-person-years-performed-by-employees-of-a-higher-education-institution-by-region-and-number-of-the-population-who-are-engineers" class="section level2">
<h2><span class="header-section-number">14.2</span> Correlation between total R&amp;D person years performed by employees of a higher education institution by region and number of the population who are engineers</h2>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb280-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb280-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb280-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb280-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb280-18" title="18">  </a>
<a class="sourceLine" id="cb280-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb280-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb280-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb280-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb280-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb280-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb280-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb280-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb280-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb280-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb280-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb280-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb280-31" title="31">  </a>
<a class="sourceLine" id="cb280-32" title="32">tb2 &lt;-<span class="st"> </span>tb1</a>
<a class="sourceLine" id="cb280-33" title="33"></a>
<a class="sourceLine" id="cb280-34" title="34">tb3 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">scale</span>()  </a>
<a class="sourceLine" id="cb280-35" title="35">  </a>
<a class="sourceLine" id="cb280-36" title="36">d &lt;-<span class="st"> </span><span class="kw">dist</span>(tb3, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>)</a>
<a class="sourceLine" id="cb280-37" title="37"></a>
<a class="sourceLine" id="cb280-38" title="38">res.hc &lt;-<span class="st"> </span><span class="kw">hclust</span>(d, <span class="dt">method =</span> <span class="st">&quot;ward.D2&quot;</span> )</a>
<a class="sourceLine" id="cb280-39" title="39"></a>
<a class="sourceLine" id="cb280-40" title="40">grp &lt;-<span class="st"> </span><span class="kw">cutree</span>(res.hc, <span class="dt">k =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb280-41" title="41"></a>
<a class="sourceLine" id="cb280-42" title="42">tb4 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp)</a>
<a class="sourceLine" id="cb280-43" title="43"></a>
<a class="sourceLine" id="cb280-44" title="44">model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(sum_edu <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb280-45" title="45"></a>
<a class="sourceLine" id="cb280-46" title="46"><span class="kw">summary</span>(model1) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb280-47" title="47"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb280-48" title="48"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb280-49" title="49">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb280-50" title="50">  <span class="dt">caption =</span> <span class="st">&#39;Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures6">Table 14.3: </span>Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-6.620101e+07</td>
<td align="right">2.06e-05</td>
<td align="right">-3.207153e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">1.200785e+02</td>
<td align="right">0.00e+00</td>
<td align="right">4.127007e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">-2.857963e+00</td>
<td align="right">0.00e+00</td>
<td align="right">-2.686799e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">0.000000e+00</td>
<td align="right">0.00e+00</td>
<td align="right">8.426335e-01</td>
<td align="right">0.4613091</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">3.300663e+04</td>
<td align="right">0.00e+00</td>
<td align="right">3.196360e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">-2.000000e-07</td>
<td align="right">2.00e-07</td>
<td align="right">-1.035078e+00</td>
<td align="right">0.3767507</td>
</tr>
<tr class="odd">
<td align="left">salary.y.y</td>
<td align="right">0.000000e+00</td>
<td align="right">0.00e+00</td>
<td align="right">1.588732e-01</td>
<td align="right">0.8838617</td>
</tr>
<tr class="even">
<td align="left">perc_women</td>
<td align="right">-2.048043e+04</td>
<td align="right">0.00e+00</td>
<td align="right">-1.887715e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">3.263440e+00</td>
<td align="right">0.00e+00</td>
<td align="right">1.834379e+12</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1">model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(sum_edu <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb281-2" title="2"></a>
<a class="sourceLine" id="cb281-3" title="3"><span class="kw">summary</span>(model2) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb281-4" title="4"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb281-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb281-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb281-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Summary of model data for group 2, number of population with 3 years or more post-secondary education &lt; 193000&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures6">Table 14.3: </span>Summary of model data for group 2, number of population with 3 years or more post-secondary education &lt; 193000</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-1.039565e+06</td>
<td align="right">5.503698e+05</td>
<td align="right">-1.8888490</td>
<td align="right">0.0639155</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">3.840863e+00</td>
<td align="right">6.272259e-01</td>
<td align="right">6.1235728</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">-5.649046e-01</td>
<td align="right">4.794746e-01</td>
<td align="right">-1.1781742</td>
<td align="right">0.2435386</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">1.570842e+00</td>
<td align="right">1.039662e-01</td>
<td align="right">15.1091537</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">5.265551e+02</td>
<td align="right">2.732082e+02</td>
<td align="right">1.9273035</td>
<td align="right">0.0588444</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">-9.880334e+04</td>
<td align="right">1.118214e+04</td>
<td align="right">-8.8358203</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.y.y</td>
<td align="right">2.899929e+00</td>
<td align="right">6.437333e-01</td>
<td align="right">4.5048608</td>
<td align="right">0.0000327</td>
</tr>
<tr class="even">
<td align="left">perc_women</td>
<td align="right">5.896028e+00</td>
<td align="right">8.907710e+01</td>
<td align="right">0.0661902</td>
<td align="right">0.9474541</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">1.640474e+00</td>
<td align="right">1.165766e+00</td>
<td align="right">1.4072073</td>
<td align="right">0.1647024</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">-8.237740e+04</td>
<td align="right">3.314969e+04</td>
<td align="right">-2.4850124</td>
<td align="right">0.0158610</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" title="1"><span class="kw">Anova</span>(model2, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb282-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb282-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb282-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb282-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<pre><code>## Note: model has aliased coefficients
##       sums of squares computed by model comparison</code></pre>
<table>
<caption><span id="tab:rndexpenditures6">Table 14.3: </span>Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">salary.x.x</td>
<td align="right">175405754.82</td>
<td align="right">1</td>
<td align="right">37.4981435</td>
<td align="right">0.0000001</td>
</tr>
<tr class="even">
<td align="left">salary.y</td>
<td align="right">6493114.71</td>
<td align="right">1</td>
<td align="right">1.3880944</td>
<td align="right">0.2435386</td>
</tr>
<tr class="odd">
<td align="left">salary.x</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">year2.x</td>
<td align="right">17375378.31</td>
<td align="right">1</td>
<td align="right">3.7144986</td>
<td align="right">0.0588444</td>
</tr>
<tr class="odd">
<td align="left">utbregno</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">365197516.66</td>
<td align="right">1</td>
<td align="right">78.0717195</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.y.y</td>
<td align="right">94928546.25</td>
<td align="right">1</td>
<td align="right">20.2937712</td>
<td align="right">0.0000327</td>
</tr>
<tr class="even">
<td align="left">perc_women</td>
<td align="right">20493.73</td>
<td align="right">1</td>
<td align="right">0.0043811</td>
<td align="right">0.9474541</td>
</tr>
<tr class="odd">
<td align="left">sum_ing</td>
<td align="right">9262969.01</td>
<td align="right">1</td>
<td align="right">1.9802323</td>
<td align="right">0.1647024</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">28886250.67</td>
<td align="right">1</td>
<td align="right">6.1752864</td>
<td align="right">0.0158610</td>
</tr>
<tr class="odd">
<td align="left">grp</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">271307665.61</td>
<td align="right">58</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" title="1">tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb284-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> salary.x.x, <span class="dt">y =</span> sum_edu, <span class="dt">colour =</span> region, <span class="dt">size =</span> year2.x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb284-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb284-4" title="4"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb284-5" title="5"><span class="st">  </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>grp) <span class="op">+</span></a>
<a class="sourceLine" id="cb284-6" title="6"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb284-7" title="7">    <span class="dt">x =</span> <span class="st">&quot;Total R&amp;D person years performed by employees of a higher education institution by region&quot;</span>,</a>
<a class="sourceLine" id="cb284-8" title="8">    <span class="dt">y =</span> <span class="st">&quot;Number of the population with 3 years or more post-secondary education&quot;</span></a>
<a class="sourceLine" id="cb284-9" title="9">  )</a></code></pre></div>
<pre><code>## Warning: Removed 92 rows containing missing values (geom_point).</code></pre>
<div class="figure"><span id="fig:rndexpenditures6"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures6-1.png" alt="Correlation between total R&amp;D person years performed by employees of a higher education institution by region and number of the population who are engineers" width="672" />
<p class="caption">
Figure 14.5: Correlation between total R&amp;D person years performed by employees of a higher education institution by region and number of the population who are engineers
</p>
</div>
</div>
<div id="correlation-between-regional-distribution-of-enterprises-rd-and-number-of-the-population-who-are-engineers" class="section level2">
<h2><span class="header-section-number">14.3</span> Correlation between regional distribution of enterprises R&amp;D and number of the population who are engineers</h2>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb286-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_ing =</span> <span class="kw">sum</span>(salary))  </a>
<a class="sourceLine" id="cb286-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-13" title="13"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_eng =</span> sum_ing <span class="op">/</span><span class="st"> </span>sum_edu)</a>
<a class="sourceLine" id="cb286-14" title="14">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-15" title="15"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb286-16" title="16">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-17" title="17"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb286-18" title="18">  </a>
<a class="sourceLine" id="cb286-19" title="19">tb1 &lt;-<span class="st"> </span>tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb286-20" title="20">  salary.x.x, </a>
<a class="sourceLine" id="cb286-21" title="21">  salary.y, </a>
<a class="sourceLine" id="cb286-22" title="22">  salary.x, </a>
<a class="sourceLine" id="cb286-23" title="23">  year2.x, </a>
<a class="sourceLine" id="cb286-24" title="24">  utbregno, </a>
<a class="sourceLine" id="cb286-25" title="25">  perc_edu, </a>
<a class="sourceLine" id="cb286-26" title="26">  sum_edu, </a>
<a class="sourceLine" id="cb286-27" title="27">  salary.y.y, </a>
<a class="sourceLine" id="cb286-28" title="28">  perc_women, </a>
<a class="sourceLine" id="cb286-29" title="29">  sum_ing, </a>
<a class="sourceLine" id="cb286-30" title="30">  perc_eng)</a>
<a class="sourceLine" id="cb286-31" title="31">  </a>
<a class="sourceLine" id="cb286-32" title="32">tb2 &lt;-<span class="st"> </span>tb1</a>
<a class="sourceLine" id="cb286-33" title="33"></a>
<a class="sourceLine" id="cb286-34" title="34">tb3 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">scale</span>()  </a>
<a class="sourceLine" id="cb286-35" title="35">  </a>
<a class="sourceLine" id="cb286-36" title="36">d &lt;-<span class="st"> </span><span class="kw">dist</span>(tb3, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>)</a>
<a class="sourceLine" id="cb286-37" title="37"></a>
<a class="sourceLine" id="cb286-38" title="38">res.hc &lt;-<span class="st"> </span><span class="kw">hclust</span>(d, <span class="dt">method =</span> <span class="st">&quot;ward.D2&quot;</span> )</a>
<a class="sourceLine" id="cb286-39" title="39"></a>
<a class="sourceLine" id="cb286-40" title="40">grp &lt;-<span class="st"> </span><span class="kw">cutree</span>(res.hc, <span class="dt">k =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb286-41" title="41"></a>
<a class="sourceLine" id="cb286-42" title="42">tb4 &lt;-<span class="st"> </span>tb2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp)</a>
<a class="sourceLine" id="cb286-43" title="43"></a>
<a class="sourceLine" id="cb286-44" title="44">model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(sum_ing <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb286-45" title="45"></a>
<a class="sourceLine" id="cb286-46" title="46"><span class="kw">summary</span>(model1) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb286-47" title="47"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-48" title="48"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb286-49" title="49">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb286-50" title="50">  <span class="dt">caption =</span> <span class="st">&#39;Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures7">Table 14.4: </span>Summary of model data for group 1, number of population with 3 years or more post-secondary education &gt; 193000</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2.028566e+07</td>
<td align="right">8.7e-06</td>
<td align="right">2.328515e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">-3.679508e+01</td>
<td align="right">0.0e+00</td>
<td align="right">-2.518763e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">8.757519e-01</td>
<td align="right">0.0e+00</td>
<td align="right">3.309505e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">0.000000e+00</td>
<td align="right">0.0e+00</td>
<td align="right">-8.432274e-01</td>
<td align="right">0.4610237</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">-1.011406e+04</td>
<td align="right">0.0e+00</td>
<td align="right">-2.323401e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">1.000000e-07</td>
<td align="right">1.0e-07</td>
<td align="right">1.035901e+00</td>
<td align="right">0.3764222</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">3.064252e-01</td>
<td align="right">0.0e+00</td>
<td align="right">1.834501e+12</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">0.000000e+00</td>
<td align="right">0.0e+00</td>
<td align="right">-1.591774e-01</td>
<td align="right">0.8836417</td>
</tr>
<tr class="odd">
<td align="left">perc_women</td>
<td align="right">6.275719e+03</td>
<td align="right">0.0e+00</td>
<td align="right">1.704962e+12</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" title="1">model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(sum_ing <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> <span class="kw">filter</span>(tb4, grp <span class="op">==</span><span class="st"> </span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb287-2" title="2"></a>
<a class="sourceLine" id="cb287-3" title="3"><span class="kw">summary</span>(model2) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb287-4" title="4"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb287-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb287-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb287-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Summary of model data for group 2, number of population with 3 years or more post-secondary education &lt; 193000&#39;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures7">Table 14.4: </span>Summary of model data for group 2, number of population with 3 years or more post-secondary education &lt; 193000</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">21196.0979826</td>
<td align="right">6.274442e+04</td>
<td align="right">0.3378164</td>
<td align="right">0.7367212</td>
</tr>
<tr class="even">
<td align="left">salary.x.x</td>
<td align="right">-0.1087238</td>
<td align="right">8.799350e-02</td>
<td align="right">-1.2355896</td>
<td align="right">0.2215925</td>
</tr>
<tr class="odd">
<td align="left">salary.y</td>
<td align="right">0.3015347</td>
<td align="right">3.633450e-02</td>
<td align="right">8.2988643</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">salary.x</td>
<td align="right">0.0278309</td>
<td align="right">2.532140e-02</td>
<td align="right">1.0991060</td>
<td align="right">0.2762633</td>
</tr>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">-11.1555186</td>
<td align="right">3.118023e+01</td>
<td align="right">-0.3577753</td>
<td align="right">0.7218102</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">-3.9728911</td>
<td align="right">1.897053e+03</td>
<td align="right">-0.0020942</td>
<td align="right">0.9983362</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">0.0201251</td>
<td align="right">1.430150e-02</td>
<td align="right">1.4072073</td>
<td align="right">0.1647024</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">0.1947262</td>
<td align="right">7.879540e-02</td>
<td align="right">2.4712903</td>
<td align="right">0.0164209</td>
</tr>
<tr class="odd">
<td align="left">perc_women</td>
<td align="right">11.9696948</td>
<td align="right">9.740607e+00</td>
<td align="right">1.2288449</td>
<td align="right">0.2240926</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">23016.3036434</td>
<td align="right">2.404771e+03</td>
<td align="right">9.5711002</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1"><span class="kw">Anova</span>(model2, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb288-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb288-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb288-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb288-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<pre><code>## Note: model has aliased coefficients
##       sums of squares computed by model comparison</code></pre>
<table>
<caption><span id="tab:rndexpenditures7">Table 14.4: </span>Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">salary.x.x</td>
<td align="right">8.760967e+04</td>
<td align="right">1</td>
<td align="right">1.5266817</td>
<td align="right">0.2215925</td>
</tr>
<tr class="even">
<td align="left">salary.y</td>
<td align="right">3.952218e+06</td>
<td align="right">1</td>
<td align="right">68.8711485</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">salary.x</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">year2.x</td>
<td align="right">7.345550e+03</td>
<td align="right">1</td>
<td align="right">0.1280032</td>
<td align="right">0.7218102</td>
</tr>
<tr class="odd">
<td align="left">utbregno</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">perc_edu</td>
<td align="right">2.516853e-01</td>
<td align="right">1</td>
<td align="right">0.0000044</td>
<td align="right">0.9983362</td>
</tr>
<tr class="odd">
<td align="left">sum_edu</td>
<td align="right">1.136370e+05</td>
<td align="right">1</td>
<td align="right">1.9802323</td>
<td align="right">0.1647024</td>
</tr>
<tr class="even">
<td align="left">salary.y.y</td>
<td align="right">3.504702e+05</td>
<td align="right">1</td>
<td align="right">6.1072758</td>
<td align="right">0.0164209</td>
</tr>
<tr class="odd">
<td align="left">perc_women</td>
<td align="right">8.665581e+04</td>
<td align="right">1</td>
<td align="right">1.5100598</td>
<td align="right">0.2240926</td>
</tr>
<tr class="even">
<td align="left">perc_eng</td>
<td align="right">5.256871e+06</td>
<td align="right">1</td>
<td align="right">91.6059592</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">grp</td>
<td align="right">NA</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">3.328370e+06</td>
<td align="right">58</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" title="1">tb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(grp) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb290-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> salary.y, <span class="dt">y =</span> sum_ing, <span class="dt">colour =</span> region, <span class="dt">size =</span> year2.x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb290-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb290-4" title="4"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb290-5" title="5"><span class="st">  </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>grp) <span class="op">+</span></a>
<a class="sourceLine" id="cb290-6" title="6"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb290-7" title="7">    <span class="dt">x =</span> <span class="st">&quot;Regional distribution of enterprises R&amp;D&quot;</span>,</a>
<a class="sourceLine" id="cb290-8" title="8">    <span class="dt">y =</span> <span class="st">&quot;Number of the population who are engineers&quot;</span></a>
<a class="sourceLine" id="cb290-9" title="9">  )</a></code></pre></div>
<pre><code>## Warning: Removed 96 rows containing missing values (geom_point).</code></pre>
<div class="figure"><span id="fig:rndexpenditures7"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures7-1.png" alt="Correlation between regional distribution of enterprises R&amp;D and number of the population who are engineers" width="672" />
<p class="caption">
Figure 14.6: Correlation between regional distribution of enterprises R&amp;D and number of the population who are engineers
</p>
</div>
</div>
<div id="f-value-for-regional-distribution-of-enterprises-rd-compared-to-the-level-of-regional-distribution-of-enterprises-rd" class="section level2">
<h2><span class="header-section-number">14.4</span> F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D</h2>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000NL_10.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-2" title="2"><span class="st">  </span><span class="kw">filter</span>(salary <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-3" title="3"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year, <span class="st">`</span><span class="dt">occupation (SSYK 2012)</span><span class="st">`</span>) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb292-4" title="4"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary))))</a>
<a class="sourceLine" id="cb292-5" title="5">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;UF0506A1_2.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-6" title="6"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year, sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">utbregno =</span> <span class="kw">sum</span>(salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-8" title="8"><span class="st">  </span><span class="kw">group_by</span>(region, year, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">perc_edu =</span> utbregno <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, region, year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-10" title="10"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">sum_edu =</span> <span class="kw">sum</span>(utbregno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-11" title="11"><span class="st">  </span><span class="kw">filter</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;post-secondary education 3 years or more (ISCED97 5A)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-12" title="12"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>))</a>
<a class="sourceLine" id="cb292-13" title="13">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002O5.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-14" title="14"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb292-15" title="15">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000002LR.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-16" title="16"><span class="st">  </span><span class="kw">right_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>))</a>
<a class="sourceLine" id="cb292-17" title="17">  </a>
<a class="sourceLine" id="cb292-18" title="18">summary_table =<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb292-19" title="19">anova_table =<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb292-20" title="20"> </a>
<a class="sourceLine" id="cb292-21" title="21"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">unique</span>(tb<span class="op">$</span><span class="st">`</span><span class="dt">occupation (SSYK 2012)</span><span class="st">`</span>)){</a>
<a class="sourceLine" id="cb292-22" title="22">  temp &lt;-<span class="st"> </span><span class="kw">filter</span>(tb, <span class="st">`</span><span class="dt">occupation (SSYK 2012)</span><span class="st">`</span> <span class="op">==</span><span class="st"> </span>i)</a>
<a class="sourceLine" id="cb292-23" title="23">  <span class="cf">if</span> (<span class="kw">dim</span>(temp)[<span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span><span class="dv">50</span>){</a>
<a class="sourceLine" id="cb292-24" title="24">    model &lt;-<span class="st"> </span><span class="kw">lm</span>(perc_women <span class="op">~</span><span class="st"> </span>salary.x.x <span class="op">+</span><span class="st"> </span>year2.x, <span class="dt">data =</span> temp)</a>
<a class="sourceLine" id="cb292-25" title="25">    summary_table &lt;-<span class="st"> </span><span class="kw">rbind</span> (summary_table, <span class="kw">mutate</span> (<span class="kw">tidy</span> (<span class="kw">summary</span> (model)), <span class="dt">ssyk =</span> i))</a>
<a class="sourceLine" id="cb292-26" title="26">    anova_table &lt;-<span class="st"> </span><span class="kw">rbind</span> (anova_table, <span class="kw">mutate</span> (<span class="kw">tidy</span> (<span class="kw">Anova</span> (model, <span class="dt">type =</span> <span class="dv">2</span>)), <span class="dt">ssyk =</span> i))</a>
<a class="sourceLine" id="cb292-27" title="27">  }</a>
<a class="sourceLine" id="cb292-28" title="28">}  </a>
<a class="sourceLine" id="cb292-29" title="29"></a>
<a class="sourceLine" id="cb292-30" title="30"><span class="kw">merge</span>(summary_table, anova_table, <span class="dt">by =</span> <span class="st">&quot;ssyk&quot;</span>, <span class="dt">all =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-31" title="31"><span class="st">  </span><span class="kw">filter</span> (term.y <span class="op">==</span><span class="st"> &quot;salary.x.x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-32" title="32"><span class="st">  </span><span class="kw">filter</span> (term.x <span class="op">==</span><span class="st"> &quot;salary.x.x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb292-33" title="33"><span class="st">  </span><span class="kw">ggplot</span> () <span class="op">+</span></a>
<a class="sourceLine" id="cb292-34" title="34"><span class="st">    </span><span class="kw">geom_point</span> (<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> estimate, <span class="dt">y =</span> statistic.y))</a></code></pre></div>
<div class="figure"><span id="fig:rndexpenditures8"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/rndexpenditures8-1.png" alt="F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D" width="672" />
<p class="caption">
Figure 14.7: F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D
</p>
</div>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb293-1" title="1"><span class="kw">merge</span>(summary_table, anova_table, <span class="dt">by =</span> <span class="st">&quot;ssyk&quot;</span>, <span class="dt">all =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb293-2" title="2"><span class="st">  </span><span class="kw">filter</span> (term.y <span class="op">==</span><span class="st"> &quot;salary.x.x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb293-3" title="3"><span class="st">  </span><span class="kw">filter</span> (term.x <span class="op">==</span><span class="st"> &quot;salary.x.x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb293-4" title="4"><span class="st">  </span><span class="kw">select</span> (ssyk, estimate, statistic.y) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb293-5" title="5"><span class="st">  </span><span class="kw">arrange</span> (<span class="kw">desc</span> (statistic.y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb293-6" title="6"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb293-7" title="7">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb293-8" title="8">  <span class="dt">caption =</span> <span class="st">&#39;Correlation F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:rndexpenditures8">Table 14.5: </span>Correlation F-value for Regional distribution of enterprises R&amp;D compared to the level of Regional distribution of enterprises R&amp;D</caption>
<thead>
<tr class="header">
<th align="left">ssyk</th>
<th align="right">estimate</th>
<th align="right">statistic.y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">911 Cleaners and helpers</td>
<td align="right">-0.0030996</td>
<td align="right">182.2383184</td>
</tr>
<tr class="even">
<td align="left">221 Medical doctors</td>
<td align="right">0.0011671</td>
<td align="right">122.5231685</td>
</tr>
<tr class="odd">
<td align="left">941 Fast-food workers, food preparation assistants</td>
<td align="right">-0.0024852</td>
<td align="right">104.3717811</td>
</tr>
<tr class="even">
<td align="left">232 Vocational education teachers</td>
<td align="right">0.0026742</td>
<td align="right">87.0970487</td>
</tr>
<tr class="odd">
<td align="left">311 Physical and engineering science technicians</td>
<td align="right">0.0009277</td>
<td align="right">72.9055322</td>
</tr>
<tr class="even">
<td align="left">512 Cooks and cold-buffet managers</td>
<td align="right">-0.0032370</td>
<td align="right">66.5884816</td>
</tr>
<tr class="odd">
<td align="left">137 Production managers in manufacturing</td>
<td align="right">0.0015297</td>
<td align="right">62.8338593</td>
</tr>
<tr class="even">
<td align="left">134 Architectural and engineering managers</td>
<td align="right">0.0021929</td>
<td align="right">61.1692588</td>
</tr>
<tr class="odd">
<td align="left">513 Waiters and bartenders</td>
<td align="right">-0.0020032</td>
<td align="right">58.0257962</td>
</tr>
<tr class="even">
<td align="left">832 Car, van and motorcycle drivers</td>
<td align="right">-0.0013658</td>
<td align="right">55.9610864</td>
</tr>
<tr class="odd">
<td align="left">831 Train operators and related workers</td>
<td align="right">0.0024045</td>
<td align="right">53.9025509</td>
</tr>
<tr class="even">
<td align="left">213 Biologists, pharmacologists and specialists in agriculture and forestry</td>
<td align="right">0.0047037</td>
<td align="right">51.6416883</td>
</tr>
<tr class="odd">
<td align="left">532 Personal care workers in health services</td>
<td align="right">-0.0008095</td>
<td align="right">50.9190498</td>
</tr>
<tr class="even">
<td align="left">514 Hairdressers, beauty and body therapists</td>
<td align="right">-0.0014734</td>
<td align="right">50.6911754</td>
</tr>
<tr class="odd">
<td align="left">345 Culinary associate professionals</td>
<td align="right">-0.0036857</td>
<td align="right">47.9421863</td>
</tr>
<tr class="even">
<td align="left">962 Newspaper distributors, janitors and other service workers</td>
<td align="right">-0.0014001</td>
<td align="right">46.7552071</td>
</tr>
<tr class="odd">
<td align="left">214 Engineering professionals</td>
<td align="right">0.0016934</td>
<td align="right">42.6919074</td>
</tr>
<tr class="even">
<td align="left">612 Animal breeders and keepers</td>
<td align="right">0.0041226</td>
<td align="right">40.8091027</td>
</tr>
<tr class="odd">
<td align="left">331 Financial and accounting associate professionals</td>
<td align="right">-0.0010927</td>
<td align="right">38.5049439</td>
</tr>
<tr class="even">
<td align="left">411 Office assistants and other secretaries</td>
<td align="right">-0.0005466</td>
<td align="right">35.3593101</td>
</tr>
<tr class="odd">
<td align="left">442 Postmen and postal facility workers</td>
<td align="right">-0.0018570</td>
<td align="right">34.9533005</td>
</tr>
<tr class="even">
<td align="left">122 Human resource managers</td>
<td align="right">0.0022329</td>
<td align="right">33.1443604</td>
</tr>
<tr class="odd">
<td align="left">138 Forestry and agricultural production managers</td>
<td align="right">0.0035502</td>
<td align="right">32.2061328</td>
</tr>
<tr class="even">
<td align="left">136 Production managers in construction and mining</td>
<td align="right">0.0007508</td>
<td align="right">31.3124199</td>
</tr>
<tr class="odd">
<td align="left">441 Library and filing clerks</td>
<td align="right">-0.0023673</td>
<td align="right">30.4650658</td>
</tr>
<tr class="even">
<td align="left">125 Sales and marketing managers</td>
<td align="right">0.0014675</td>
<td align="right">27.7781933</td>
</tr>
<tr class="odd">
<td align="left">132 Supply, logistics and transport managers</td>
<td align="right">0.0012752</td>
<td align="right">23.7529612</td>
</tr>
<tr class="even">
<td align="left">242 Organisation analysts, policy administrators and human resource specialists</td>
<td align="right">-0.0007277</td>
<td align="right">22.7969692</td>
</tr>
<tr class="odd">
<td align="left">817 Wood processing and papermaking plant operators</td>
<td align="right">0.0012658</td>
<td align="right">22.4301002</td>
</tr>
<tr class="even">
<td align="left">141 Primary and secondary schools and adult education managers</td>
<td align="right">0.0012615</td>
<td align="right">21.8622482</td>
</tr>
<tr class="odd">
<td align="left">133 Research and development managers</td>
<td align="right">0.0025322</td>
<td align="right">20.3768786</td>
</tr>
<tr class="even">
<td align="left">819 Process control technicians</td>
<td align="right">0.0011769</td>
<td align="right">20.0741880</td>
</tr>
<tr class="odd">
<td align="left">0002 occupations unidentifiable</td>
<td align="right">0.0005205</td>
<td align="right">18.8624174</td>
</tr>
<tr class="even">
<td align="left">711 Carpenters, bricklayers and construction workers</td>
<td align="right">-0.0001930</td>
<td align="right">18.0597988</td>
</tr>
<tr class="odd">
<td align="left">613 Mixed crop and animal breeders</td>
<td align="right">0.0016658</td>
<td align="right">17.2620922</td>
</tr>
<tr class="even">
<td align="left">952 Street and market vendors</td>
<td align="right">-0.0046963</td>
<td align="right">16.0411516</td>
</tr>
<tr class="odd">
<td align="left">534 Attendants, personal assistants and related workers</td>
<td align="right">-0.0008334</td>
<td align="right">15.9973139</td>
</tr>
<tr class="even">
<td align="left">533 Health care assistants</td>
<td align="right">-0.0009220</td>
<td align="right">15.3757533</td>
</tr>
<tr class="odd">
<td align="left">234 Primary- and pre-school teachers</td>
<td align="right">-0.0004133</td>
<td align="right">15.2368418</td>
</tr>
<tr class="even">
<td align="left">129 Administration and service managers not elsewhere classified</td>
<td align="right">0.0009603</td>
<td align="right">14.9740988</td>
</tr>
<tr class="odd">
<td align="left">516 Other service related workers</td>
<td align="right">0.0019281</td>
<td align="right">14.9655338</td>
</tr>
<tr class="even">
<td align="left">312 Construction and manufacturing supervisors</td>
<td align="right">0.0005142</td>
<td align="right">14.7842494</td>
</tr>
<tr class="odd">
<td align="left">241 Accountants, financial analysts and fund managers</td>
<td align="right">-0.0010991</td>
<td align="right">13.8078711</td>
</tr>
<tr class="even">
<td align="left">179 Other services managers not elsewhere classified</td>
<td align="right">0.0012453</td>
<td align="right">13.7755966</td>
</tr>
<tr class="odd">
<td align="left">522 Shop staff</td>
<td align="right">-0.0005233</td>
<td align="right">13.4411826</td>
</tr>
<tr class="even">
<td align="left">933 Dockers and ground personnel</td>
<td align="right">-0.0012789</td>
<td align="right">13.0784229</td>
</tr>
<tr class="odd">
<td align="left">351 ICT operations and user support technicians</td>
<td align="right">0.0006981</td>
<td align="right">13.0560672</td>
</tr>
<tr class="even">
<td align="left">262 Museum curators and librarians and related professionals</td>
<td align="right">-0.0011223</td>
<td align="right">12.2777588</td>
</tr>
<tr class="odd">
<td align="left">761 Butchers, bakers and food processors</td>
<td align="right">-0.0026786</td>
<td align="right">12.1783273</td>
</tr>
<tr class="even">
<td align="left">121 Finance managers</td>
<td align="right">-0.0010096</td>
<td align="right">12.0177082</td>
</tr>
<tr class="odd">
<td align="left">266 Social work and counselling professionals</td>
<td align="right">-0.0005584</td>
<td align="right">11.9755481</td>
</tr>
<tr class="even">
<td align="left">713 Painters, Lacquerers, Chimney-sweepers and related trades workers</td>
<td align="right">-0.0006715</td>
<td align="right">10.7393561</td>
</tr>
<tr class="odd">
<td align="left">135 Real estate and head of administration manager</td>
<td align="right">0.0012192</td>
<td align="right">10.5601787</td>
</tr>
<tr class="even">
<td align="left">721 Sheet and structural metal workers, moulders and welders, and related workers</td>
<td align="right">-0.0002850</td>
<td align="right">10.3858424</td>
</tr>
<tr class="odd">
<td align="left">332 Insurance advisers, sales and purchasing agents</td>
<td align="right">0.0007277</td>
<td align="right">9.8611424</td>
</tr>
<tr class="even">
<td align="left">216 Architects and surveyors</td>
<td align="right">0.0010543</td>
<td align="right">8.5326492</td>
</tr>
<tr class="odd">
<td align="left">815 Machine operators, textile, fur and leather products</td>
<td align="right">-0.0020888</td>
<td align="right">8.1456890</td>
</tr>
<tr class="even">
<td align="left">523 Cashiers and related clerks</td>
<td align="right">-0.0009472</td>
<td align="right">7.8879684</td>
</tr>
<tr class="odd">
<td align="left">265 Creative and performing artists</td>
<td align="right">-0.0012359</td>
<td align="right">7.7239943</td>
</tr>
<tr class="even">
<td align="left">816 Machine operators, food and related products</td>
<td align="right">-0.0014418</td>
<td align="right">6.6018433</td>
</tr>
<tr class="odd">
<td align="left">223 Nursing professionals (cont.)</td>
<td align="right">-0.0003366</td>
<td align="right">6.5061862</td>
</tr>
<tr class="even">
<td align="left">151 Health care managers</td>
<td align="right">-0.0005436</td>
<td align="right">6.3475749</td>
</tr>
<tr class="odd">
<td align="left">264 Authors, journalists and linguists</td>
<td align="right">0.0007703</td>
<td align="right">6.2738005</td>
</tr>
<tr class="even">
<td align="left">834 Mobile plant operators</td>
<td align="right">0.0004162</td>
<td align="right">5.8211196</td>
</tr>
<tr class="odd">
<td align="left">235 Teaching professionals not elsewhere classified</td>
<td align="right">0.0005917</td>
<td align="right">5.6025008</td>
</tr>
<tr class="even">
<td align="left">174 Sports, leisure and wellness managers</td>
<td align="right">0.0019824</td>
<td align="right">5.4125857</td>
</tr>
<tr class="odd">
<td align="left">021 Non-commissioned armed forces officers</td>
<td align="right">-0.0014815</td>
<td align="right">5.3387915</td>
</tr>
<tr class="even">
<td align="left">535 Dental nurses</td>
<td align="right">-0.0001425</td>
<td align="right">5.3242471</td>
</tr>
<tr class="odd">
<td align="left">212 Mathematicians, actuaries and statisticians</td>
<td align="right">-0.0024328</td>
<td align="right">5.1766496</td>
</tr>
<tr class="even">
<td align="left">172 Restaurant managers</td>
<td align="right">-0.0006944</td>
<td align="right">4.6592000</td>
</tr>
<tr class="odd">
<td align="left">173 Retail and wholesale trade managers</td>
<td align="right">0.0005362</td>
<td align="right">4.2604295</td>
</tr>
<tr class="even">
<td align="left">742 Electronics and telecommunications installers and repairers</td>
<td align="right">0.0002631</td>
<td align="right">4.1515159</td>
</tr>
<tr class="odd">
<td align="left">741 Electrical equipment installers and repairers</td>
<td align="right">0.0000985</td>
<td align="right">4.1380495</td>
</tr>
<tr class="even">
<td align="left">344 Driving instructors and other instructors</td>
<td align="right">0.0007466</td>
<td align="right">4.0426757</td>
</tr>
<tr class="odd">
<td align="left">912 Washers, window cleaners and other cleaning workers</td>
<td align="right">-0.0011824</td>
<td align="right">4.0388717</td>
</tr>
<tr class="even">
<td align="left">159 Other social services managers</td>
<td align="right">0.0005640</td>
<td align="right">3.8322867</td>
</tr>
<tr class="odd">
<td align="left">511 Cabin crew, guides and related workers</td>
<td align="right">-0.0010675</td>
<td align="right">3.8092027</td>
</tr>
<tr class="even">
<td align="left">931 Construction labourers</td>
<td align="right">-0.0003903</td>
<td align="right">3.7495964</td>
</tr>
<tr class="odd">
<td align="left">321 Medical and pharmaceutical technicians</td>
<td align="right">0.0007264</td>
<td align="right">3.7423088</td>
</tr>
<tr class="even">
<td align="left">226 Dentists</td>
<td align="right">0.0005561</td>
<td align="right">3.5781833</td>
</tr>
<tr class="odd">
<td align="left">323 Complementary medicine therapists and associate professionals</td>
<td align="right">0.0016120</td>
<td align="right">3.5630309</td>
</tr>
<tr class="even">
<td align="left">325 Dental hygienists</td>
<td align="right">-0.0002400</td>
<td align="right">3.4556858</td>
</tr>
<tr class="odd">
<td align="left">732 Printing trades workers</td>
<td align="right">-0.0007322</td>
<td align="right">3.3387800</td>
</tr>
<tr class="even">
<td align="left">421 Croupiers, debt collectors and related workers</td>
<td align="right">-0.0017245</td>
<td align="right">3.3166418</td>
</tr>
<tr class="odd">
<td align="left">131 Information and communications technology service managers</td>
<td align="right">0.0005547</td>
<td align="right">3.2281010</td>
</tr>
<tr class="even">
<td align="left">149 Education managers not elsewhere classified</td>
<td align="right">0.0013691</td>
<td align="right">2.8201834</td>
</tr>
<tr class="odd">
<td align="left">224 Psychologists and psychotherapists</td>
<td align="right">0.0003523</td>
<td align="right">2.7719052</td>
</tr>
<tr class="even">
<td align="left">752 Wood treaters, cabinet-makers and related trades workers</td>
<td align="right">-0.0004144</td>
<td align="right">2.7489510</td>
</tr>
<tr class="odd">
<td align="left">336 Police officers</td>
<td align="right">0.0002912</td>
<td align="right">2.6853439</td>
</tr>
<tr class="even">
<td align="left">112 Managing directors and chief executives</td>
<td align="right">0.0004770</td>
<td align="right">2.6272481</td>
</tr>
<tr class="odd">
<td align="left">123 Administration and planning managers</td>
<td align="right">0.0009542</td>
<td align="right">2.5931760</td>
</tr>
<tr class="even">
<td align="left">813 Machine operators, chemical and pharmaceutical products</td>
<td align="right">0.0015989</td>
<td align="right">2.5770693</td>
</tr>
<tr class="odd">
<td align="left">541 Other surveillance and security workers</td>
<td align="right">-0.0004414</td>
<td align="right">2.3015605</td>
</tr>
<tr class="even">
<td align="left">443 Elected representatives</td>
<td align="right">0.0014827</td>
<td align="right">2.2531501</td>
</tr>
<tr class="odd">
<td align="left">228 Specialists in health care not elsewhere classified</td>
<td align="right">-0.0002941</td>
<td align="right">2.0996543</td>
</tr>
<tr class="even">
<td align="left">812 Metal processing and finishing plant operators</td>
<td align="right">-0.0003770</td>
<td align="right">2.0290928</td>
</tr>
<tr class="odd">
<td align="left">731 Precision-instrument makers and handicraft workers</td>
<td align="right">-0.0010310</td>
<td align="right">1.9894240</td>
</tr>
<tr class="even">
<td align="left">218 Specialists within environmental and health protection</td>
<td align="right">0.0004343</td>
<td align="right">1.9890362</td>
</tr>
<tr class="odd">
<td align="left">921 Berry pickers and planters</td>
<td align="right">0.0010203</td>
<td align="right">1.9250652</td>
</tr>
<tr class="even">
<td align="left">334 Administrative and specialized secretaries</td>
<td align="right">0.0005837</td>
<td align="right">1.9073946</td>
</tr>
<tr class="odd">
<td align="left">524 Event seller and telemarketers</td>
<td align="right">-0.0007815</td>
<td align="right">1.8993126</td>
</tr>
<tr class="even">
<td align="left">152 Managers in social and curative care</td>
<td align="right">0.0005667</td>
<td align="right">1.7933247</td>
</tr>
<tr class="odd">
<td align="left">153 Elderly care managers</td>
<td align="right">-0.0002735</td>
<td align="right">1.7135293</td>
</tr>
<tr class="even">
<td align="left">818 Other stationary plant and machine operators</td>
<td align="right">-0.0008982</td>
<td align="right">1.6778246</td>
</tr>
<tr class="odd">
<td align="left">111 Legislators and senior officials</td>
<td align="right">0.0005527</td>
<td align="right">1.6102363</td>
</tr>
<tr class="even">
<td align="left">154 Managers and leaders within religious bodies</td>
<td align="right">0.0010633</td>
<td align="right">1.4201370</td>
</tr>
<tr class="odd">
<td align="left">225 Veterinarians</td>
<td align="right">0.0004125</td>
<td align="right">1.3545138</td>
</tr>
<tr class="even">
<td align="left">333 Business services agents</td>
<td align="right">-0.0002360</td>
<td align="right">1.2612291</td>
</tr>
<tr class="odd">
<td align="left">217 Designers</td>
<td align="right">-0.0005639</td>
<td align="right">1.1260004</td>
</tr>
<tr class="even">
<td align="left">231 University and higher education teachers</td>
<td align="right">-0.0004262</td>
<td align="right">1.1018661</td>
</tr>
<tr class="odd">
<td align="left">233 Secondary education teachers</td>
<td align="right">-0.0001749</td>
<td align="right">1.0323567</td>
</tr>
<tr class="even">
<td align="left">814 Machine operators, rubber, plastic and paper products</td>
<td align="right">-0.0005303</td>
<td align="right">0.8203157</td>
</tr>
<tr class="odd">
<td align="left">124 Information, communication and public relations managers</td>
<td align="right">0.0004612</td>
<td align="right">0.8178175</td>
</tr>
<tr class="even">
<td align="left">227 Naprapaths, physiotherapists, occupational therapists</td>
<td align="right">-0.0001312</td>
<td align="right">0.7864043</td>
</tr>
<tr class="odd">
<td align="left">211 Physicists and chemists</td>
<td align="right">0.0006338</td>
<td align="right">0.7193156</td>
</tr>
<tr class="even">
<td align="left">622 Aquaculture and fishery workers</td>
<td align="right">-0.0008068</td>
<td align="right">0.7039453</td>
</tr>
<tr class="odd">
<td align="left">011 Commissioned armed forces officers</td>
<td align="right">0.0002307</td>
<td align="right">0.6772185</td>
</tr>
<tr class="even">
<td align="left">251 ICT architects, systems analysts and test managers</td>
<td align="right">-0.0001260</td>
<td align="right">0.6656660</td>
</tr>
<tr class="odd">
<td align="left">833 Heavy truck and bus drivers</td>
<td align="right">0.0000787</td>
<td align="right">0.6401266</td>
</tr>
<tr class="even">
<td align="left">267 Religious professionals and deacons</td>
<td align="right">0.0002932</td>
<td align="right">0.5786666</td>
</tr>
<tr class="odd">
<td align="left">811 Mining and mineral processing plant operators</td>
<td align="right">-0.0001851</td>
<td align="right">0.5550635</td>
</tr>
<tr class="even">
<td align="left">821 Assemblers</td>
<td align="right">-0.0002720</td>
<td align="right">0.5443326</td>
</tr>
<tr class="odd">
<td align="left">352 Broadcasting and audio-visual technicians</td>
<td align="right">-0.0004866</td>
<td align="right">0.4993140</td>
</tr>
<tr class="even">
<td align="left">611 Market gardeners and crop growers</td>
<td align="right">-0.0001863</td>
<td align="right">0.4709511</td>
</tr>
<tr class="odd">
<td align="left">342 Athletes, fitness instructors and recreational workers</td>
<td align="right">-0.0001664</td>
<td align="right">0.3152640</td>
</tr>
<tr class="even">
<td align="left">621 Forestry and related workers</td>
<td align="right">0.0002310</td>
<td align="right">0.2997644</td>
</tr>
<tr class="odd">
<td align="left">031 Armed forces occupations, other ranks</td>
<td align="right">-0.0001374</td>
<td align="right">0.2907770</td>
</tr>
<tr class="even">
<td align="left">723 Machinery mechanics and fitters</td>
<td align="right">0.0000882</td>
<td align="right">0.2798201</td>
</tr>
<tr class="odd">
<td align="left">341 Social work and religious associate professionals</td>
<td align="right">-0.0001656</td>
<td align="right">0.2547258</td>
</tr>
<tr class="even">
<td align="left">243 Marketing and public relations professionals</td>
<td align="right">0.0001437</td>
<td align="right">0.2438027</td>
</tr>
<tr class="odd">
<td align="left">712 Roofers, floor layers, plumbers and pipefitters</td>
<td align="right">0.0000232</td>
<td align="right">0.2127881</td>
</tr>
<tr class="even">
<td align="left">422 Client information clerks</td>
<td align="right">0.0001878</td>
<td align="right">0.1498584</td>
</tr>
<tr class="odd">
<td align="left">161 Financial and insurance managers</td>
<td align="right">-0.0001440</td>
<td align="right">0.1480319</td>
</tr>
<tr class="even">
<td align="left">171 Hotel and conference managers</td>
<td align="right">-0.0002032</td>
<td align="right">0.1276805</td>
</tr>
<tr class="odd">
<td align="left">142 Preschool managers</td>
<td align="right">-0.0000713</td>
<td align="right">0.1227402</td>
</tr>
<tr class="even">
<td align="left">835 Ships deck crews and related workers</td>
<td align="right">0.0002358</td>
<td align="right">0.1223260</td>
</tr>
<tr class="odd">
<td align="left">335 Tax and related government associate professionals</td>
<td align="right">0.0000722</td>
<td align="right">0.1218028</td>
</tr>
<tr class="even">
<td align="left">222 Nursing professionals</td>
<td align="right">-0.0000272</td>
<td align="right">0.0765304</td>
</tr>
<tr class="odd">
<td align="left">261 Legal professionals</td>
<td align="right">-0.0000507</td>
<td align="right">0.0310529</td>
</tr>
<tr class="even">
<td align="left">515 Building caretakers and related workers</td>
<td align="right">0.0000439</td>
<td align="right">0.0291504</td>
</tr>
<tr class="odd">
<td align="left">932 Manufacturing labourers</td>
<td align="right">0.0000717</td>
<td align="right">0.0250665</td>
</tr>
<tr class="even">
<td align="left">432 Stores and transport clerks</td>
<td align="right">-0.0000307</td>
<td align="right">0.0199936</td>
</tr>
<tr class="odd">
<td align="left">531 Child care workers and teachers aides</td>
<td align="right">-0.0000088</td>
<td align="right">0.0042005</td>
</tr>
<tr class="even">
<td align="left">324 Veterinary assistants</td>
<td align="right">-0.0000259</td>
<td align="right">0.0036212</td>
</tr>
<tr class="odd">
<td align="left">343 Photographers, interior decorators and entertainers</td>
<td align="right">0.0000203</td>
<td align="right">0.0017386</td>
</tr>
<tr class="even">
<td align="left">722 Blacksmiths, toolmakers and related trades workers</td>
<td align="right">-0.0000076</td>
<td align="right">0.0007481</td>
</tr>
<tr class="odd">
<td align="left">961 Recycling collectors</td>
<td align="right">0.0000043</td>
<td align="right">0.0003329</td>
</tr>
<tr class="even">
<td align="left">315 Ship and aircraft controllers and technicians</td>
<td align="right">-0.0000033</td>
<td align="right">0.0000489</td>
</tr>
<tr class="odd">
<td align="left">753 Tailors, upholsterers and leather craftsmen</td>
<td align="right">0.0000048</td>
<td align="right">0.0000291</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-correlation-between-the-proportion-of-physical-and-engineering-science-technicians-who-are-women-and-the-number-of-the-population-in-the-region-year-2014-2018.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-a.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SCB-Engineers-Jonkoping.pdf", "SCB-Engineers-Jonkoping.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
