<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 SSYK 214 | SCB Engineers Jonkoping</title>
  <meta name="description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 SSYK 214 | SCB Engineers Jonkoping" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  <meta name="github-repo" content="MikaelLundqvist/SCB-Engineers-Jonkoping" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 SSYK 214 | SCB Engineers Jonkoping" />
  
  <meta name="twitter:description" content="Statistics from Statistics Sweden regarding the labour market, salaries and other relevant data from engineers, primarily in Jönköping county." />
  

<meta name="author" content="Mikael Lundqvist" />


<meta name="date" content="2019-08-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="civilingenjorsutbildning-sun-2000.html">
<link rel="next" href="ssyk-311.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SCB Engineers Jonkoping</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="help-functions.html"><a href="help-functions.html"><i class="fa fa-check"></i><b>3</b> Help functions</a></li>
<li class="chapter" data-level="4" data-path="natural-sciences.html"><a href="natural-sciences.html"><i class="fa fa-check"></i><b>4</b> Natural sciences</a></li>
<li class="chapter" data-level="5" data-path="number-of-physical-and-engineering-science-technicians-in-jonkoping-county.html"><a href="number-of-physical-and-engineering-science-technicians-in-jonkoping-county.html"><i class="fa fa-check"></i><b>5</b> Number of Physical and engineering science technicians in Jönköping county</a></li>
<li class="chapter" data-level="6" data-path="percent-women-in-the-countys.html"><a href="percent-women-in-the-countys.html"><i class="fa fa-check"></i><b>6</b> Percent women in the countys</a></li>
<li class="chapter" data-level="7" data-path="engineering-professionals.html"><a href="engineering-professionals.html"><i class="fa fa-check"></i><b>7</b> Engineering professionals</a></li>
<li class="chapter" data-level="8" data-path="civilingenjorsutbildning-sun-2000.html"><a href="civilingenjorsutbildning-sun-2000.html"><i class="fa fa-check"></i><b>8</b> Civilingenjörsutbildning SUN 2000</a></li>
<li class="chapter" data-level="9" data-path="ssyk-214.html"><a href="ssyk-214.html"><i class="fa fa-check"></i><b>9</b> SSYK 214</a><ul>
<li class="chapter" data-level="9.1" data-path="ssyk-214.html"><a href="ssyk-214.html#average-monthly-salary-sek-by-region"><i class="fa fa-check"></i><b>9.1</b> Average monthly salary, SEK by region</a></li>
<li class="chapter" data-level="9.2" data-path="ssyk-214.html"><a href="ssyk-214.html#number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2014---2018"><i class="fa fa-check"></i><b>9.2</b> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.3" data-path="ssyk-214.html"><a href="ssyk-214.html#number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2003---2013"><i class="fa fa-check"></i><b>9.3</b> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.4" data-path="ssyk-214.html"><a href="ssyk-214.html#age-distribution-in-the-different-countys"><i class="fa fa-check"></i><b>9.4</b> Age distribution in the different countys</a></li>
<li class="chapter" data-level="9.5" data-path="ssyk-214.html"><a href="ssyk-214.html#sector-distribution-in-the-different-countys"><i class="fa fa-check"></i><b>9.5</b> Sector distribution in the different countys</a></li>
<li class="chapter" data-level="9.6" data-path="ssyk-214.html"><a href="ssyk-214.html#education-distribution-for-engineers"><i class="fa fa-check"></i><b>9.6</b> Education distribution for engineers</a></li>
<li class="chapter" data-level="9.7" data-path="ssyk-214.html"><a href="ssyk-214.html#average-monthly-pay-increase-by-occuption-year-2000---2013"><i class="fa fa-check"></i><b>9.7</b> Average monthly pay increase by occuption year 2000 - 2013</a></li>
<li class="chapter" data-level="9.8" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-year-2000---2013"><i class="fa fa-check"></i><b>9.8</b> SSYK 214, Architects, engineers and related professionals, Year 2000 - 2013</a></li>
<li class="chapter" data-level="9.9" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-year-2014---2018"><i class="fa fa-check"></i><b>9.9</b> SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.10" data-path="ssyk-214.html"><a href="ssyk-214.html#ssyk-214-architects-engineers-and-related-professionals-by-region-year-2000---2018"><i class="fa fa-check"></i><b>9.10</b> SSYK 214, Architects, engineers and related professionals by region, Year 2000 - 2018</a></li>
<li class="chapter" data-level="9.11" data-path="ssyk-214.html"><a href="ssyk-214.html#level-of-education-ssyk-214-architects-engineers-and-related-professionals"><i class="fa fa-check"></i><b>9.11</b> Level of education , SSYK 214, Architects, engineers and related professionals</a></li>
<li class="chapter" data-level="9.12" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018"><i class="fa fa-check"></i><b>9.12</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</a></li>
<li class="chapter" data-level="9.13" data-path="ssyk-214.html"><a href="ssyk-214.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2003---2013"><i class="fa fa-check"></i><b>9.13</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2003 - 2013</a></li>
<li class="chapter" data-level="9.14" data-path="ssyk-214.html"><a href="ssyk-214.html#animations-ssyk-214-architects-engineers-and-related-professionals"><i class="fa fa-check"></i><b>9.14</b> Animations , SSYK 214, Architects, engineers and related professionals</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ssyk-311.html"><a href="ssyk-311.html"><i class="fa fa-check"></i><b>10</b> SSYK 311</a><ul>
<li class="chapter" data-level="10.1" data-path="ssyk-311.html"><a href="ssyk-311.html#average-monthly-salary-sek-by-region-1"><i class="fa fa-check"></i><b>10.1</b> Average monthly salary, SEK by region</a></li>
<li class="chapter" data-level="10.2" data-path="ssyk-311.html"><a href="ssyk-311.html#number-of-men-and-women-in-ssyk-311-and-the-percentage-of-women-in-ssyk-311-year-2014---2018"><i class="fa fa-check"></i><b>10.2</b> Number of men and women in SSYK 311 and the percentage of women in SSYK 311 Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.3" data-path="ssyk-311.html"><a href="ssyk-311.html#number-of-men-and-women-in-ssyk-311-and-the-percentage-of-women-in-ssyk-311-year-2003---2013"><i class="fa fa-check"></i><b>10.3</b> Number of men and women in SSYK 311 and the percentage of women in SSYK 311 Year 2003 - 2013</a></li>
<li class="chapter" data-level="10.4" data-path="ssyk-311.html"><a href="ssyk-311.html#age-distribution-in-the-different-countys-1"><i class="fa fa-check"></i><b>10.4</b> Age distribution in the different countys</a></li>
<li class="chapter" data-level="10.5" data-path="ssyk-311.html"><a href="ssyk-311.html#sector-distribution-in-the-different-countys-1"><i class="fa fa-check"></i><b>10.5</b> Sector distribution in the different countys</a></li>
<li class="chapter" data-level="10.6" data-path="ssyk-311.html"><a href="ssyk-311.html#education-distribution-for-engineers-1"><i class="fa fa-check"></i><b>10.6</b> Education distribution for engineers</a></li>
<li class="chapter" data-level="10.7" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-year-2000---2013"><i class="fa fa-check"></i><b>10.7</b> SSYK 311, Physical and engineering science technicians, Year 2000 - 2013</a></li>
<li class="chapter" data-level="10.8" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-year-2014---2018"><i class="fa fa-check"></i><b>10.8</b> SSYK 311, Physical and engineering science technicians, Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.9" data-path="ssyk-311.html"><a href="ssyk-311.html#ssyk-311-physical-and-engineering-science-technicians-by-region-year-2000---2018"><i class="fa fa-check"></i><b>10.9</b> SSYK 311, Physical and engineering science technicians by region, Year 2000 - 2018</a></li>
<li class="chapter" data-level="10.10" data-path="ssyk-311.html"><a href="ssyk-311.html#level-of-education-ssyk-311-physical-and-engineering-science-technicians"><i class="fa fa-check"></i><b>10.10</b> Level of education , SSYK 311, Physical and engineering science technicians</a></li>
<li class="chapter" data-level="10.11" data-path="ssyk-311.html"><a href="ssyk-311.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018-1"><i class="fa fa-check"></i><b>10.11</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</a></li>
<li class="chapter" data-level="10.12" data-path="ssyk-311.html"><a href="ssyk-311.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2003---2013-1"><i class="fa fa-check"></i><b>10.12</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2003 - 2013</a></li>
<li class="chapter" data-level="10.13" data-path="ssyk-311.html"><a href="ssyk-311.html#animations-ssyk-214-architects-engineers-and-related-professionals-1"><i class="fa fa-check"></i><b>10.13</b> Animations , SSYK 214, Architects, engineers and related professionals</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="average-monthly-pay-year-1991-2015.html"><a href="average-monthly-pay-year-1991-2015.html"><i class="fa fa-check"></i><b>11</b> Average monthly pay Year 1991 - 2015</a></li>
<li class="chapter" data-level="12" data-path="utbildningsniva.html"><a href="utbildningsniva.html"><i class="fa fa-check"></i><b>12</b> Utbildningsnivå</a><ul>
<li class="chapter" data-level="12.1" data-path="utbildningsniva.html"><a href="utbildningsniva.html#the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018-2"><i class="fa fa-check"></i><b>12.1</b> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="appendix-a.html"><a href="appendix-a.html"><i class="fa fa-check"></i><b>13</b> Appendix A</a></li>
<li class="chapter" data-level="14" data-path="appendix-b.html"><a href="appendix-b.html"><i class="fa fa-check"></i><b>14</b> Appendix B</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/MikaelLundqvist/SCB-Engineers-Jonkoping" target="blank">Github</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SCB Engineers Jonkoping</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ssyk-214" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> SSYK 214</h1>
<div id="average-monthly-salary-sek-by-region" class="section level2">
<h2><span class="header-section-number">9.1</span> Average monthly salary, SEK by region</h2>
<p>Genomsnittlig grund- och månadslön samt kvinnors lön i procent av mäns lön efter region sektor, yrkesgrupp (SSYK 2012) och kön. År 2014 - 2018
Månadslön
Samtliga sektorer
214 Cilvilingenjörsyrken
Kön totalt
2017</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="kw">readfile</span> (<span class="st">&quot;000000CG_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-2" title="2"><span class="st">  </span><span class="kw">left_join</span>(nuts, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span> =<span class="st"> &quot;NUTS2&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-3" title="3"><span class="st">  </span><span class="kw">right_join</span>(map_ln_n, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;Länskod&quot;</span> =<span class="st"> &quot;lnkod_n&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb39-5" title="5"><span class="st">    </span><span class="kw">geom_polygon</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> ggplot_long, <span class="dt">y =</span> ggplot_lat, <span class="dt">group =</span> lnkod, <span class="dt">fill =</span> relsalary)) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-6" title="6"><span class="st">    </span><span class="kw">coord_equal</span>() </a></code></pre></div>
<div class="figure"><span id="fig:214sweden"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214sweden-1.png" alt="Engineers salaries in the different countys" width="672" />
<p class="caption">
Figure 9.1: Engineers salaries in the different countys
</p>
</div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">salary_<span class="dv">2017</span> &lt;-<span class="st"> </span><span class="kw">readfile</span> (<span class="st">&quot;000000CG_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-2" title="2"><span class="st">  </span><span class="kw">left_join</span>(nuts, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span> =<span class="st"> &quot;NUTS2&quot;</span>))</a>
<a class="sourceLine" id="cb40-3" title="3"></a>
<a class="sourceLine" id="cb40-4" title="4"><span class="kw">readfile</span> (<span class="st">&quot;000000NL_3.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb40-5" title="5"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb40-6" title="6"><span class="st">  </span><span class="kw">summarise</span> (<span class="dt">perc_women =</span> <span class="kw">perc_women</span> (salary)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">perc_women_n =</span> <span class="kw">as.numeric</span>(<span class="kw">sub</span>(<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, perc_women))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-8" title="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lnkod_n =</span> <span class="kw">as.numeric</span>(<span class="kw">substr</span>(region, <span class="dv">1</span>,<span class="dv">2</span>)))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-9" title="9"><span class="st">  </span><span class="kw">right_join</span>(salary_<span class="dv">2017</span>, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;lnkod_n&quot;</span> =<span class="st"> &quot;Länskod&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-10" title="10"><span class="st">  </span><span class="kw">ggscatter</span>(<span class="dt">x =</span> <span class="st">&quot;relsalary&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;perc_women_n&quot;</span>, </a>
<a class="sourceLine" id="cb40-11" title="11">    <span class="dt">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="dt">conf.int =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb40-12" title="12">    <span class="dt">cor.coef =</span> <span class="ot">TRUE</span>, <span class="dt">cor.method =</span> <span class="st">&quot;pearson&quot;</span>)    </a></code></pre></div>
<div class="figure"><span id="fig:women"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/women-1.png" alt="The correlation between the proportion of engineers who are women and the salaries of engineers in the region." width="672" />
<p class="caption">
Figure 9.2: The correlation between the proportion of engineers who are women and the salaries of engineers in the region.
</p>
</div>
</div>
<div id="number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2014---2018" class="section level2">
<h2><span class="header-section-number">9.2</span> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2014 - 2018</h2>
<p>Average basic salary, monthly salary and women´s salary as a percentage of men´s salary by sector, occupational group (SSYK 2012), sex and educational level (SUN). Year 2014 - 2018
Number of employees
All sectors
214, Architects, engineers and related professionals</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;000000CV_3.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb41-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (year) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb41-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb41-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year2)) <span class="op">+</span></a>
<a class="sourceLine" id="cb41-5" title="5"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">y =</span> salary, <span class="dt">colour =</span> sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb41-6" title="6"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">y =</span> perc_women <span class="op">*</span><span class="st"> </span><span class="dv">2000</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb41-7" title="7"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">sec.axis =</span> <span class="kw">sec_axis</span>(<span class="op">~</span><span class="st"> </span>. <span class="op">*</span><span class="st"> </span><span class="fl">0.0005</span>, <span class="dt">name =</span> <span class="st">&quot;Percent women [%]&quot;</span>))</a></code></pre></div>
<div class="figure"><span id="fig:214percwomen"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214percwomen-1.png" alt="Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2014 - 2018" width="672" />
<p class="caption">
Figure 9.3: Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2014 - 2018
</p>
</div>
</div>
<div id="number-of-men-and-women-in-ssyk-214-and-the-percentage-of-women-in-ssyk-214-year-2003---2013" class="section level2">
<h2><span class="header-section-number">9.3</span> Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2003 - 2013</h2>
<p>Average basic salary, monthly salary and women´s salary as a percentage of men´s salary by sector, occupational group (SSYK), sex and educational level (SUN). Year 2003 - 2013
Number of employees
All sectors
214, Architects, engineers and related professionals</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;AM0110B4.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb42-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (year) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb42-3" title="3"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb42-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year2)) <span class="op">+</span></a>
<a class="sourceLine" id="cb42-5" title="5"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">y =</span> salary, <span class="dt">colour =</span> sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb42-6" title="6"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">y =</span> perc_women <span class="op">*</span><span class="st"> </span><span class="dv">2000</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb42-7" title="7"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">sec.axis =</span> <span class="kw">sec_axis</span>(<span class="op">~</span><span class="st"> </span>. <span class="op">*</span><span class="st"> </span><span class="fl">0.0005</span>, <span class="dt">name =</span> <span class="st">&quot;Percent women [%]&quot;</span>))</a></code></pre></div>
<div class="figure"><span id="fig:214percwomen2"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214percwomen2-1.png" alt="Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2003 - 2013" width="672" />
<p class="caption">
Figure 9.4: Number of men and women in SSYK 214 and the percentage of women in SSYK 214 Year 2003 - 2013
</p>
</div>
</div>
<div id="age-distribution-in-the-different-countys" class="section level2">
<h2><span class="header-section-number">9.4</span> Age distribution in the different countys</h2>
<p>Employees 16-64 years by region of work, occupation (3-digit SSYK 2012), age and sex. Year 2014 - 2017
occupation=214, Architects, engineers and related professionals</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;000000NK.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year2 <span class="op">==</span><span class="st"> </span><span class="dv">2017</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb43-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb43-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb43-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb43-5" title="5"><span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> (age2 <span class="op">+</span><span class="st"> </span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">y =</span> salary, <span class="dt">color =</span> region)) <span class="op">+</span></a>
<a class="sourceLine" id="cb43-6" title="6"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb43-7" title="7"><span class="st">    </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>sex)</a></code></pre></div>
<div class="figure"><span id="fig:214age"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214age-1.png" alt="The age distribution in the different countys for engineers, year 2017" width="672" />
<p class="caption">
Figure 9.5: The age distribution in the different countys for engineers, year 2017
</p>
</div>
</div>
<div id="sector-distribution-in-the-different-countys" class="section level2">
<h2><span class="header-section-number">9.5</span> Sector distribution in the different countys</h2>
<p>Employees 16-64 years by region of work, occupation (3-digit SSYK 2012), sector and sex. Year 2014 - 2017
occupation=214, Architects, engineers and related professionals</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;000000RM_1.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb44-2" title="2"><span class="st">  </span><span class="kw">filter</span>(year2 <span class="op">==</span><span class="st"> </span><span class="dv">2017</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb44-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lnkod_n =</span> <span class="kw">substr</span>(region, <span class="dv">1</span>,<span class="dv">2</span>))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb44-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> lnkod_n, <span class="dt">y =</span> salary, <span class="dt">fill =</span> sector)) <span class="op">+</span></a>
<a class="sourceLine" id="cb44-5" title="5"><span class="st">    </span><span class="kw">geom_col</span>(<span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb44-6" title="6"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb44-7" title="7"><span class="st">    </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>sex)</a></code></pre></div>
<div class="figure"><span id="fig:214sector"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214sector-1.png" alt="The sector distribution in the different countys for engineers, year 2017" width="672" />
<p class="caption">
Figure 9.6: The sector distribution in the different countys for engineers, year 2017
</p>
</div>
</div>
<div id="education-distribution-for-engineers" class="section level2">
<h2><span class="header-section-number">9.6</span> Education distribution for engineers</h2>
<p>Number of employees by sector, occuptional (SSYK 2012), sex, level of education and year
214 Engineering professionals
All sectors
Year 2017</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1">edu &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000CV_1.csv&quot;</span>)</a>
<a class="sourceLine" id="cb45-2" title="2">edu<span class="op">$</span><span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">as.factor</span>(edu<span class="op">$</span><span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb45-3" title="3">edu<span class="op">$</span><span class="st">`</span><span class="dt">level of education</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">factor</span>(edu<span class="op">$</span><span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, <span class="kw">levels</span>(edu<span class="op">$</span><span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>)[<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">5</span>, <span class="dv">1</span>)])</a>
<a class="sourceLine" id="cb45-4" title="4">edu <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb45-5" title="5"><span class="st">  </span><span class="kw">filter</span>(year2 <span class="op">==</span><span class="st"> </span><span class="dv">2017</span>) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb45-6" title="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">`</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span>, <span class="dt">y =</span> salary, <span class="dt">fill =</span> <span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-7" title="7"><span class="st">    </span><span class="kw">geom_col</span>(<span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-8" title="8"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-9" title="9"><span class="st">    </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>sex) </a></code></pre></div>
<div class="figure"><span id="fig:214edu"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/214edu-1.png" alt="The education distribution for engineers, year 2017" width="672" />
<p class="caption">
Figure 9.7: The education distribution for engineers, year 2017
</p>
</div>
</div>
<div id="average-monthly-pay-increase-by-occuption-year-2000---2013" class="section level2">
<h2><span class="header-section-number">9.7</span> Average monthly pay increase by occuption year 2000 - 2013</h2>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP), SEK by occuptional (SSYK 2012), age, sex and year, Year 2000 - 2013<br />
age=total<br />
sex=total</p>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP), SEK by occuptional (SSYK 2012), age, sex and year, Year 2014 - 2018<br />
age=total<br />
sex=total</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">readfile</span> (<span class="st">&quot;AM0103E6.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb46-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occupational group (SSYK)</span><span class="st">`</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb46-3" title="3"><span class="st">  </span><span class="kw">summarise</span> (<span class="dt">tot =</span> <span class="kw">tot_dev</span> (salary)) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb46-4" title="4"><span class="st">  </span><span class="kw">arrange</span> (<span class="kw">desc</span> (tot)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb46-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb46-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb46-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Average monthly pay increase by occuption (SSYK 2012), Year 2000 - 2013&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:occuptionpay">Table 9.1: </span>Average monthly pay increase by occuption (SSYK 2012), Year 2000 - 2013</caption>
<thead>
<tr class="header">
<th align="left">occupational group (SSYK)</th>
<th align="left">tot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">249 Psychologists, social work and related professionals</td>
<td align="left">71.1%</td>
</tr>
<tr class="even">
<td align="left">723 Machinery mechanics and fitters</td>
<td align="left">70.4%</td>
</tr>
<tr class="odd">
<td align="left">822 Chemical-products machine operators</td>
<td align="left">66.8%</td>
</tr>
<tr class="even">
<td align="left">829 Other machine operators and assemblers</td>
<td align="left">66.7%</td>
</tr>
<tr class="odd">
<td align="left">222 Health professionals (except nursing)</td>
<td align="left">66.6%</td>
</tr>
<tr class="even">
<td align="left">0002 occupations unidentifiable</td>
<td align="left">63.1%</td>
</tr>
<tr class="odd">
<td align="left">722 Blacksmiths, tool-makers and related trades workers</td>
<td align="left">62.0%</td>
</tr>
<tr class="even">
<td align="left">121 Directors and chief executives</td>
<td align="left">61.5%</td>
</tr>
<tr class="odd">
<td align="left">419 Other office clerks</td>
<td align="left">61.4%</td>
</tr>
<tr class="even">
<td align="left">828 Assemblers</td>
<td align="left">61.1%</td>
</tr>
<tr class="odd">
<td align="left">731 Precision workers in metal and related materials</td>
<td align="left">60.8%</td>
</tr>
<tr class="even">
<td align="left">815 Chemical-processing-plant operators</td>
<td align="left">60.7%</td>
</tr>
<tr class="odd">
<td align="left">522 Shop and stall salespersons and demonstrators</td>
<td align="left">60.5%</td>
</tr>
<tr class="even">
<td align="left">131 Managers of small enterprises</td>
<td align="left">59.7%</td>
</tr>
<tr class="odd">
<td align="left">321 Agronomy and forestry technicians</td>
<td align="left">58.0%</td>
</tr>
<tr class="even">
<td align="left">212 Mathematicians and statisticians</td>
<td align="left">57.6%</td>
</tr>
<tr class="odd">
<td align="left">221 Life science professionals</td>
<td align="left">57.3%</td>
</tr>
<tr class="even">
<td align="left">919 Other sales and services elementary occupations</td>
<td align="left">56.9%</td>
</tr>
<tr class="odd">
<td align="left">324 Life science technicians</td>
<td align="left">56.7%</td>
</tr>
<tr class="even">
<td align="left">413 Stores and transport clerks</td>
<td align="left">56.4%</td>
</tr>
<tr class="odd">
<td align="left">827 Food and related products machine operators</td>
<td align="left">55.7%</td>
</tr>
<tr class="even">
<td align="left">331 Pre-primary education teaching associate professionals</td>
<td align="left">55.4%</td>
</tr>
<tr class="odd">
<td align="left">323 Nursing associate professionals</td>
<td align="left">54.9%</td>
</tr>
<tr class="even">
<td align="left">246 Religious professionals</td>
<td align="left">54.4%</td>
</tr>
<tr class="odd">
<td align="left">341 Finance and sales associate professionals</td>
<td align="left">54.3%</td>
</tr>
<tr class="even">
<td align="left">311 Physical and engineering science technicians</td>
<td align="left">54.2%</td>
</tr>
<tr class="odd">
<td align="left">512 Housekeeping and restaurant services workers</td>
<td align="left">54.2%</td>
</tr>
<tr class="even">
<td align="left">347 Artistic, entertainment and sports associate professionals</td>
<td align="left">54.1%</td>
</tr>
<tr class="odd">
<td align="left">122 Production and operations managers</td>
<td align="left">52.9%</td>
</tr>
<tr class="even">
<td align="left">348 Religious associate professionals</td>
<td align="left">52.4%</td>
</tr>
<tr class="odd">
<td align="left">713 Building finishers and related trades workers</td>
<td align="left">51.3%</td>
</tr>
<tr class="even">
<td align="left">0000 All</td>
<td align="left">51.2%</td>
</tr>
<tr class="odd">
<td align="left">123 Other specialist managers</td>
<td align="left">51.2%</td>
</tr>
<tr class="even">
<td align="left">914 Doorkeepers, newspaper and package deliverers and related workers</td>
<td align="left">50.9%</td>
</tr>
<tr class="odd">
<td align="left">315 Safety and quality inspectors</td>
<td align="left">50.8%</td>
</tr>
<tr class="even">
<td align="left">412 Numerical clerks</td>
<td align="left">50.8%</td>
</tr>
<tr class="odd">
<td align="left">724 Electrical and electronic equipment mechanics and fitters</td>
<td align="left">50.7%</td>
</tr>
<tr class="even">
<td align="left">346 Social work associate professionals</td>
<td align="left">50.3%</td>
</tr>
<tr class="odd">
<td align="left">342 Business services agents and trade brokers</td>
<td align="left">50.2%</td>
</tr>
<tr class="even">
<td align="left">343 Administrative associate professionals</td>
<td align="left">50.2%</td>
</tr>
<tr class="odd">
<td align="left">825 Printing-, binding- and paper-products machine operators</td>
<td align="left">50.0%</td>
</tr>
<tr class="even">
<td align="left">312 Computer associate professionals</td>
<td align="left">48.5%</td>
</tr>
<tr class="odd">
<td align="left">243 Archivists, librarians and related information professionals</td>
<td align="left">48.2%</td>
</tr>
<tr class="even">
<td align="left">912 Helpers and cleaners</td>
<td align="left">47.7%</td>
</tr>
<tr class="odd">
<td align="left">422 Client information clerks</td>
<td align="left">47.6%</td>
</tr>
<tr class="even">
<td align="left">513 Personal care and related workers</td>
<td align="left">47.3%</td>
</tr>
<tr class="odd">
<td align="left">913 Helpers in restaurants</td>
<td align="left">47.0%</td>
</tr>
<tr class="even">
<td align="left">831 Locomotive-engine drivers and related worker</td>
<td align="left">46.9%</td>
</tr>
<tr class="odd">
<td align="left">712 Building frame and related trades workers</td>
<td align="left">46.8%</td>
</tr>
<tr class="even">
<td align="left">816 Power-production and related plant operators</td>
<td align="left">45.2%</td>
</tr>
<tr class="odd">
<td align="left">411 Office secretaries and data entry operators</td>
<td align="left">44.4%</td>
</tr>
<tr class="even">
<td align="left">112 Senior officials of special-interest organisations</td>
<td align="left">43.9%</td>
</tr>
<tr class="odd">
<td align="left">241 Business professionals</td>
<td align="left">43.0%</td>
</tr>
<tr class="even">
<td align="left">514 Other personal services workers</td>
<td align="left">42.7%</td>
</tr>
<tr class="odd">
<td align="left">344 Customs, tax and related government associate professionals</td>
<td align="left">42.0%</td>
</tr>
<tr class="even">
<td align="left">231 College, university and higher education teaching professionals</td>
<td align="left">41.8%</td>
</tr>
<tr class="odd">
<td align="left">211 Physicists, chemists and related professionals</td>
<td align="left">41.6%</td>
</tr>
<tr class="even">
<td align="left">245 Writers and creative or performing artists</td>
<td align="left">40.7%</td>
</tr>
<tr class="odd">
<td align="left">832 Motor-vehicle drivers</td>
<td align="left">40.6%</td>
</tr>
<tr class="even">
<td align="left">214 Architects, engineers and related professionals</td>
<td align="left">40.3%</td>
</tr>
<tr class="odd">
<td align="left">721 Metal moulders, welders, sheet-metal workers, structural-metal preparers and related trades workers</td>
<td align="left">39.9%</td>
</tr>
<tr class="even">
<td align="left">322 Health associate professionals (except nursing)</td>
<td align="left">39.3%</td>
</tr>
<tr class="odd">
<td align="left">223 Nursing and midwifery professionals</td>
<td align="left">39.2%</td>
</tr>
<tr class="even">
<td align="left">313 Optical and electronic equipment operators</td>
<td align="left">38.9%</td>
</tr>
<tr class="odd">
<td align="left">515 Protective services workers</td>
<td align="left">38.7%</td>
</tr>
<tr class="even">
<td align="left">821 Metal- and mineral-products machine operators</td>
<td align="left">38.6%</td>
</tr>
<tr class="odd">
<td align="left">332 Other teaching associate professionals</td>
<td align="left">37.1%</td>
</tr>
<tr class="even">
<td align="left">233 Primary education teaching professionals</td>
<td align="left">36.2%</td>
</tr>
<tr class="odd">
<td align="left">743 Garment and related trades workers</td>
<td align="left">35.8%</td>
</tr>
<tr class="even">
<td align="left">242 Legal professionals</td>
<td align="left">35.7%</td>
</tr>
<tr class="odd">
<td align="left">421 Cashiers, tellers and related clerks</td>
<td align="left">35.7%</td>
</tr>
<tr class="even">
<td align="left">833 Agricultural and other mobile-plant operators</td>
<td align="left">35.5%</td>
</tr>
<tr class="odd">
<td align="left">213 Computing professionals</td>
<td align="left">35.4%</td>
</tr>
<tr class="even">
<td align="left">234 Special education teaching professionals</td>
<td align="left">34.6%</td>
</tr>
<tr class="odd">
<td align="left">235 Other teaching professionals</td>
<td align="left">34.5%</td>
</tr>
<tr class="even">
<td align="left">511 Travel attendants and related workers</td>
<td align="left">34.3%</td>
</tr>
<tr class="odd">
<td align="left">933 Transport labourers and freight handlers</td>
<td align="left">34.0%</td>
</tr>
<tr class="even">
<td align="left">248 Administrative professionals of special-interest organisations</td>
<td align="left">33.7%</td>
</tr>
<tr class="odd">
<td align="left">244 Social science and linguistics professionals (except social work professionals)</td>
<td align="left">33.0%</td>
</tr>
<tr class="even">
<td align="left">232 Secondary education teaching professionals</td>
<td align="left">32.1%</td>
</tr>
<tr class="odd">
<td align="left">414 Library and filing clerks</td>
<td align="left">31.2%</td>
</tr>
<tr class="even">
<td align="left">314 Ship and aircraft controllers and technicians</td>
<td align="left">29.5%</td>
</tr>
<tr class="odd">
<td align="left">915 Garbage collectors and related labourers</td>
<td align="left">27.9%</td>
</tr>
<tr class="even">
<td align="left">611 Market gardeners and crop growers</td>
<td align="left">27.1%</td>
</tr>
<tr class="odd">
<td align="left">814 Wood-processing- and papermaking-plant operators</td>
<td align="left">26.6%</td>
</tr>
<tr class="even">
<td align="left">932 Manufacturing labourers</td>
<td align="left">25.4%</td>
</tr>
<tr class="odd">
<td align="left">824 Wood-products machine operators</td>
<td align="left">23.9%</td>
</tr>
<tr class="even">
<td align="left">714 Painters, building structure cleaners and related trades workers</td>
<td align="left">22.7%</td>
</tr>
<tr class="odd">
<td align="left">734 Craft printing and related trades workers</td>
<td align="left">22.5%</td>
</tr>
<tr class="even">
<td align="left">612 Animal producers and related workers</td>
<td align="left">21.1%</td>
</tr>
<tr class="odd">
<td align="left">823 Rubber- and plastic-products machine operators</td>
<td align="left">15.7%</td>
</tr>
<tr class="even">
<td align="left">247 Public service administrative professionals</td>
<td align="left">15.1%</td>
</tr>
<tr class="odd">
<td align="left">415 Mail carriers and sorting clerks</td>
<td align="left">13.6%</td>
</tr>
<tr class="even">
<td align="left">124 Foreman</td>
<td align="left">13.1%</td>
</tr>
<tr class="odd">
<td align="left">111 Legislators and senior government officials</td>
<td align="left">0%</td>
</tr>
<tr class="even">
<td align="left">834 Ships´ deck crews and related workers</td>
<td align="left">0%</td>
</tr>
<tr class="odd">
<td align="left">931 Mining and construction labourers</td>
<td align="left">0%</td>
</tr>
<tr class="even">
<td align="left">812 Metal-processing-plant operators</td>
<td align="left">-6.58%</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">readfile</span> (<span class="st">&quot;00000031.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb47-2" title="2"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb47-3" title="3"><span class="st">  </span><span class="kw">summarise</span> (<span class="dt">tot =</span> <span class="kw">parse_number</span> (<span class="kw">tot_dev</span> (salary))) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="st">  </span><span class="kw">arrange</span> (<span class="kw">desc</span> (tot)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb47-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb47-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Average monthly pay increase by occuption (SSYK 2012), Year 2014 - 2018&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:occuptionpay">Table 9.1: </span>Average monthly pay increase by occuption (SSYK 2012), Year 2014 - 2018</caption>
<thead>
<tr class="header">
<th align="left">occuptional (SSYK 2012)</th>
<th align="right">tot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">222 Nursing professionals</td>
<td align="right">27.600</td>
</tr>
<tr class="even">
<td align="left">149 Education managers not elsewhere classified</td>
<td align="right">26.400</td>
</tr>
<tr class="odd">
<td align="left">343 Photographers, interior decorators and entertainers</td>
<td align="right">24.800</td>
</tr>
<tr class="even">
<td align="left">443 Elected representatives</td>
<td align="right">19.500</td>
</tr>
<tr class="odd">
<td align="left">334 Administrative and specialized secretaries</td>
<td align="right">19.200</td>
</tr>
<tr class="even">
<td align="left">266 Social work and counselling professionals</td>
<td align="right">18.400</td>
</tr>
<tr class="odd">
<td align="left">171 Hotel and conference managers</td>
<td align="right">18.300</td>
</tr>
<tr class="even">
<td align="left">161 Financial and insurance managers</td>
<td align="right">18.100</td>
</tr>
<tr class="odd">
<td align="left">173 Retail and wholesale trade managers</td>
<td align="right">17.800</td>
</tr>
<tr class="even">
<td align="left">121 Finance managers</td>
<td align="right">17.700</td>
</tr>
<tr class="odd">
<td align="left">223 Nursing professionals (cont.)</td>
<td align="right">17.700</td>
</tr>
<tr class="even">
<td align="left">122 Human resource managers</td>
<td align="right">17.600</td>
</tr>
<tr class="odd">
<td align="left">138 Forestry and agricultural production managers</td>
<td align="right">17.300</td>
</tr>
<tr class="even">
<td align="left">132 Supply, logistics and transport managers</td>
<td align="right">17.200</td>
</tr>
<tr class="odd">
<td align="left">141 Primary and secondary schools and adult education managers</td>
<td align="right">16.700</td>
</tr>
<tr class="even">
<td align="left">142 Preschool managers</td>
<td align="right">16.000</td>
</tr>
<tr class="odd">
<td align="left">152 Managers in social and curative care</td>
<td align="right">15.600</td>
</tr>
<tr class="even">
<td align="left">234 Primary- and pre-school teachers</td>
<td align="right">15.200</td>
</tr>
<tr class="odd">
<td align="left">136 Production managers in construction and mining</td>
<td align="right">15.000</td>
</tr>
<tr class="even">
<td align="left">344 Driving instructors and other instructors</td>
<td align="right">14.800</td>
</tr>
<tr class="odd">
<td align="left">123 Administration and planning managers</td>
<td align="right">14.400</td>
</tr>
<tr class="even">
<td align="left">153 Elderly care managers</td>
<td align="right">14.100</td>
</tr>
<tr class="odd">
<td align="left">174 Sports, leisure and wellness managers</td>
<td align="right">14.100</td>
</tr>
<tr class="even">
<td align="left">267 Religious professionals and deacons</td>
<td align="right">14.100</td>
</tr>
<tr class="odd">
<td align="left">265 Creative and performing artists</td>
<td align="right">13.600</td>
</tr>
<tr class="even">
<td align="left">179 Other services managers not elsewhere classified</td>
<td align="right">13.400</td>
</tr>
<tr class="odd">
<td align="left">228 Specialists in health care not elsewhere classified</td>
<td align="right">13.400</td>
</tr>
<tr class="even">
<td align="left">312 Construction and manufacturing supervisors</td>
<td align="right">13.400</td>
</tr>
<tr class="odd">
<td align="left">131 Information and communications technology service managers</td>
<td align="right">13.200</td>
</tr>
<tr class="even">
<td align="left">321 Medical and pharmaceutical technicians</td>
<td align="right">12.300</td>
</tr>
<tr class="odd">
<td align="left">335 Tax and related government associate professionals</td>
<td align="right">12.300</td>
</tr>
<tr class="even">
<td align="left">134 Architectural and engineering managers</td>
<td align="right">12.200</td>
</tr>
<tr class="odd">
<td align="left">217 Designers</td>
<td align="right">12.200</td>
</tr>
<tr class="even">
<td align="left">151 Health care managers</td>
<td align="right">11.800</td>
</tr>
<tr class="odd">
<td align="left">311 Physical and engineering science technicians</td>
<td align="right">11.700</td>
</tr>
<tr class="even">
<td align="left">224 Psychologists and psychotherapists</td>
<td align="right">10.900</td>
</tr>
<tr class="odd">
<td align="left">262 Museum curators and librarians and related professionals</td>
<td align="right">10.600</td>
</tr>
<tr class="even">
<td align="left">125 Sales and marketing managers</td>
<td align="right">10.400</td>
</tr>
<tr class="odd">
<td align="left">233 Secondary education teachers</td>
<td align="right">10.300</td>
</tr>
<tr class="even">
<td align="left">159 Other social services managers</td>
<td align="right">10.200</td>
</tr>
<tr class="odd">
<td align="left">332 Insurance advisers, sales and purchasing agents</td>
<td align="right">9.870</td>
</tr>
<tr class="even">
<td align="left">218 Specialists within environmental and health protection</td>
<td align="right">9.800</td>
</tr>
<tr class="odd">
<td align="left">212 Mathematicians, actuaries and statisticians</td>
<td align="right">9.740</td>
</tr>
<tr class="even">
<td align="left">324 Veterinary assistants</td>
<td align="right">9.490</td>
</tr>
<tr class="odd">
<td align="left">0000 All</td>
<td align="right">9.440</td>
</tr>
<tr class="even">
<td align="left">524 Event seller and telemarketers</td>
<td align="right">9.440</td>
</tr>
<tr class="odd">
<td align="left">241 Accountants, financial analysts and fund managers</td>
<td align="right">9.430</td>
</tr>
<tr class="even">
<td align="left">411 Office assistants and other secretaries</td>
<td align="right">9.190</td>
</tr>
<tr class="odd">
<td align="left">341 Social work and religious associate professionals</td>
<td align="right">9.030</td>
</tr>
<tr class="even">
<td align="left">226 Dentists</td>
<td align="right">8.980</td>
</tr>
<tr class="odd">
<td align="left">231 University and higher education teachers</td>
<td align="right">8.920</td>
</tr>
<tr class="even">
<td align="left">345 Culinary associate professionals</td>
<td align="right">8.700</td>
</tr>
<tr class="odd">
<td align="left">331 Financial and accounting associate professionals</td>
<td align="right">8.610</td>
</tr>
<tr class="even">
<td align="left">251 ICT architects, systems analysts and test managers</td>
<td align="right">8.310</td>
</tr>
<tr class="odd">
<td align="left">124 Information, communication and public relations managers</td>
<td align="right">8.280</td>
</tr>
<tr class="even">
<td align="left">261 Legal professionals</td>
<td align="right">8.190</td>
</tr>
<tr class="odd">
<td align="left">325 Dental hygienists</td>
<td align="right">8.160</td>
</tr>
<tr class="even">
<td align="left">213 Biologists, pharmacologists and specialists in agriculture and forestry</td>
<td align="right">8.140</td>
</tr>
<tr class="odd">
<td align="left">232 Vocational education teachers</td>
<td align="right">7.740</td>
</tr>
<tr class="even">
<td align="left">242 Organisation analysts, policy administrators and human resource specialists</td>
<td align="right">7.590</td>
</tr>
<tr class="odd">
<td align="left">137 Production managers in manufacturing</td>
<td align="right">7.540</td>
</tr>
<tr class="even">
<td align="left">154 Managers and leaders within religious bodies</td>
<td align="right">7.390</td>
</tr>
<tr class="odd">
<td align="left">214 Engineering professionals</td>
<td align="right">7.240</td>
</tr>
<tr class="even">
<td align="left">211 Physicists and chemists</td>
<td align="right">6.820</td>
</tr>
<tr class="odd">
<td align="left">422 Client information clerks</td>
<td align="right">6.430</td>
</tr>
<tr class="even">
<td align="left">421 Croupiers, debt collectors and related workers</td>
<td align="right">6.010</td>
</tr>
<tr class="odd">
<td align="left">112 Managing directors and chief executives</td>
<td align="right">5.840</td>
</tr>
<tr class="even">
<td align="left">133 Research and development managers</td>
<td align="right">5.320</td>
</tr>
<tr class="odd">
<td align="left">135 Real estate and head of administration manager</td>
<td align="right">5.170</td>
</tr>
<tr class="even">
<td align="left">333 Business services agents</td>
<td align="right">5.100</td>
</tr>
<tr class="odd">
<td align="left">352 Broadcasting and audio-visual technicians</td>
<td align="right">4.790</td>
</tr>
<tr class="even">
<td align="left">129 Administration and service managers not elsewhere classified</td>
<td align="right">4.100</td>
</tr>
<tr class="odd">
<td align="left">243 Marketing and public relations professionals</td>
<td align="right">4.070</td>
</tr>
<tr class="even">
<td align="left">351 ICT operations and user support technicians</td>
<td align="right">3.630</td>
</tr>
<tr class="odd">
<td align="left">227 Naprapaths, physiotherapists, occupational therapists</td>
<td align="right">3.230</td>
</tr>
<tr class="even">
<td align="left">315 Ship and aircraft controllers and technicians</td>
<td align="right">3.190</td>
</tr>
<tr class="odd">
<td align="left">264 Authors, journalists and linguists</td>
<td align="right">2.250</td>
</tr>
<tr class="even">
<td align="left">342 Athletes, fitness instructors and recreational workers</td>
<td align="right">2.110</td>
</tr>
<tr class="odd">
<td align="left">216 Architects and surveyors</td>
<td align="right">2.080</td>
</tr>
<tr class="even">
<td align="left">172 Restaurant managers</td>
<td align="right">0.917</td>
</tr>
<tr class="odd">
<td align="left">441 Library and filing clerks</td>
<td align="right">-0.402</td>
</tr>
<tr class="even">
<td align="left">225 Veterinarians</td>
<td align="right">-0.467</td>
</tr>
<tr class="odd">
<td align="left">235 Teaching professionals not elsewhere classified</td>
<td align="right">-2.720</td>
</tr>
<tr class="even">
<td align="left">0002 occupations unidentifiable</td>
<td align="right">-4.510</td>
</tr>
<tr class="odd">
<td align="left">111 Legislators and senior officials</td>
<td align="right">-7.040</td>
</tr>
<tr class="even">
<td align="left">511 Cabin crew, guides and related workers</td>
<td align="right">-7.610</td>
</tr>
<tr class="odd">
<td align="left">221 Medical doctors</td>
<td align="right">-8.990</td>
</tr>
</tbody>
</table>
</div>
<div id="ssyk-214-architects-engineers-and-related-professionals-year-2000---2013" class="section level2">
<h2><span class="header-section-number">9.8</span> SSYK 214, Architects, engineers and related professionals, Year 2000 - 2013</h2>
<p>Average monthly pay, non-manual workers private sector (SLP) by occupational
group (SSYK) age and sex. Year 2000 - 2013
Average monthly pay (total pay), non-manual workers private sector (SLP), SEK
by occupational group (SSYK), age, sex and year</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9_1.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb48-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age4 =</span> (age3 <span class="op">+</span><span class="st"> </span>age2) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-7" title="7"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occupational group (SSYK)</span><span class="st">`</span>, age, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb48-8" title="8"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))  </a></code></pre></div>
<pre><code>## Warning: Grouping rowwise data frame strips rowwise nature</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">tb <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb50-2" title="2"><span class="st">  </span><span class="kw">ggplot</span> () <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb50-3" title="3"><span class="st">    </span><span class="kw">geom_point</span> (<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2,<span class="dt">y =</span> <span class="kw">log</span>(salary), <span class="dt">colour =</span> age, <span class="dt">shape=</span>sex))  </a></code></pre></div>
<div class="figure"><span id="fig:ssyk00-13"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/ssyk00-13-1.png" alt="SSYK 214, Architects, engineers and related professionals, Year 2000 - 2013" width="672" />
<p class="caption">
Figure 9.8: SSYK 214, Architects, engineers and related professionals, Year 2000 - 2013
</p>
</div>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span><span class="kw">poly</span>(age4, <span class="dv">3</span>), <span class="dt">data =</span> tb)</a></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">bind_cols</span>(tb, <span class="kw">as_tibble</span>(<span class="kw">exp</span>(<span class="kw">predict</span>(model, tb, <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>))))</a>
<a class="sourceLine" id="cb52-2" title="2"></a>
<a class="sourceLine" id="cb52-3" title="3">tb <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb52-4" title="4"><span class="st">  </span><span class="kw">ggplot</span> () <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb52-5" title="5"><span class="st">    </span><span class="kw">geom_point</span> (<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2,<span class="dt">y =</span> <span class="kw">log</span>(fit), <span class="dt">colour =</span> age, <span class="dt">shape=</span>sex))</a></code></pre></div>
<div class="figure">
<img src="SCB-Engineers-Jonkoping_files/figure-html/ssyk00-13_2-1.png" alt="SSYK, Year 2000 - 2013" width="672" />
<p class="caption">
(#fig:ssyk00-13_2)SSYK, Year 2000 - 2013
</p>
</div>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb53-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb53-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb53-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_2)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-39.3602913</td>
<td align="right">1.4040096</td>
<td align="right">-28.034204</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">0.0248351</td>
<td align="right">0.0006997</td>
<td align="right">35.492228</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">sexwomen</td>
<td align="right">-0.0745348</td>
<td align="right">0.0056586</td>
<td align="right">-13.171933</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)1</td>
<td align="right">2.1477927</td>
<td align="right">0.0437199</td>
<td align="right">49.126166</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)2</td>
<td align="right">-1.3140489</td>
<td align="right">0.0439104</td>
<td align="right">-29.925667</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)3</td>
<td align="right">0.1728549</td>
<td align="right">0.0437183</td>
<td align="right">3.953832</td>
<td align="right">0.0001018</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb54-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb54-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>)  </a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_2)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2</td>
<td align="right">2.4060060</td>
<td align="right">1</td>
<td align="right">1259.6982</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0.3313822</td>
<td align="right">1</td>
<td align="right">173.4998</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)</td>
<td align="right">6.3536207</td>
<td align="right">3</td>
<td align="right">1108.8424</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">0.4488467</td>
<td align="right">235</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9_2.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb55-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age4 =</span> (age3 <span class="op">+</span><span class="st"> </span>age2) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-7" title="7"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occupational group (SSYK)</span><span class="st">`</span>, age, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb55-8" title="8"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))  </a></code></pre></div>
<pre><code>## Warning: Grouping rowwise data frame strips rowwise nature</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> `</span><span class="dt">occupational group (SSYK)</span><span class="st">`</span> <span class="op">+</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span><span class="kw">poly</span>(age4, <span class="dv">3</span>), <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb57-2" title="2">    </a>
<a class="sourceLine" id="cb57-3" title="3"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb57-4" title="4"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb57-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb57-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb57-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_2)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-48.9181797</td>
<td align="right">0.4450215</td>
<td align="right">-109.9231939</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>121 Directors and chief executives</td>
<td align="right">0.6843097</td>
<td align="right">0.0097694</td>
<td align="right">70.0459713</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>122 Production and operations managers</td>
<td align="right">0.1497668</td>
<td align="right">0.0077836</td>
<td align="right">19.2414263</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>123 Other specialist managers</td>
<td align="right">0.3561121</td>
<td align="right">0.0078044</td>
<td align="right">45.6299353</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>124 Foreman</td>
<td align="right">-0.0781592</td>
<td align="right">0.0118826</td>
<td align="right">-6.5776448</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>131 Managers of small enterprises</td>
<td align="right">-0.0251403</td>
<td align="right">0.0078604</td>
<td align="right">-3.1983603</td>
<td align="right">0.0013867</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>211 Physicists, chemists and related professionals</td>
<td align="right">0.2084204</td>
<td align="right">0.0081189</td>
<td align="right">25.6711740</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>212 Mathematicians and statisticians</td>
<td align="right">0.2004032</td>
<td align="right">0.0348837</td>
<td align="right">5.7448944</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>213 Computing professionals</td>
<td align="right">0.1512162</td>
<td align="right">0.0076259</td>
<td align="right">19.8291953</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>214 Architects, engineers and related professionals</td>
<td align="right">0.1216738</td>
<td align="right">0.0076417</td>
<td align="right">15.9223550</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>221 Life science professionals</td>
<td align="right">0.1249274</td>
<td align="right">0.0129063</td>
<td align="right">9.6795668</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>222 Health professionals (except nursing)</td>
<td align="right">0.3540252</td>
<td align="right">0.0081056</td>
<td align="right">43.6768676</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>223 Nursing and midwifery professionals</td>
<td align="right">-0.0537161</td>
<td align="right">0.0096257</td>
<td align="right">-5.5804691</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>231 College, university and higher education teaching professionals</td>
<td align="right">0.0520675</td>
<td align="right">0.0103711</td>
<td align="right">5.0204408</td>
<td align="right">0.0000005</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>232 Secondary education teaching professionals</td>
<td align="right">-0.2092601</td>
<td align="right">0.0081292</td>
<td align="right">-25.7418084</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>233 Primary education teaching professionals</td>
<td align="right">-0.2351593</td>
<td align="right">0.0091908</td>
<td align="right">-25.5864570</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>235 Other teaching professionals</td>
<td align="right">-0.1512582</td>
<td align="right">0.0088117</td>
<td align="right">-17.1655476</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>241 Business professionals</td>
<td align="right">0.1536239</td>
<td align="right">0.0075793</td>
<td align="right">20.2689603</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>242 Legal professionals</td>
<td align="right">0.3756703</td>
<td align="right">0.0087341</td>
<td align="right">43.0119789</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>244 Social science and linguistics professionals (except social work professionals)</td>
<td align="right">-0.0037496</td>
<td align="right">0.0845070</td>
<td align="right">-0.0443704</td>
<td align="right">0.9646101</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>245 Writers and creative or performing artists</td>
<td align="right">-0.0242627</td>
<td align="right">0.0075641</td>
<td align="right">-3.2076131</td>
<td align="right">0.0013429</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>246 Religious professionals</td>
<td align="right">-0.0330001</td>
<td align="right">0.0081970</td>
<td align="right">-4.0258803</td>
<td align="right">0.0000572</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>247 Public service administrative professionals</td>
<td align="right">-0.0042949</td>
<td align="right">0.0490043</td>
<td align="right">-0.0876426</td>
<td align="right">0.9301626</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>248 Administrative professionals of special-interest organisations</td>
<td align="right">-0.0107107</td>
<td align="right">0.0080066</td>
<td align="right">-1.3377348</td>
<td align="right">0.1810151</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>249 Psychologists, social work and related professionals</td>
<td align="right">-0.1350674</td>
<td align="right">0.0102828</td>
<td align="right">-13.1353089</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>311 Physical and engineering science technicians</td>
<td align="right">-0.0704933</td>
<td align="right">0.0075566</td>
<td align="right">-9.3286738</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>312 Computer associate professionals</td>
<td align="right">-0.0709126</td>
<td align="right">0.0076020</td>
<td align="right">-9.3281629</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>313 Optical and electronic equipment operators</td>
<td align="right">-0.2000192</td>
<td align="right">0.0095361</td>
<td align="right">-20.9750036</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>314 Ship and aircraft controllers and technicians</td>
<td align="right">0.3906773</td>
<td align="right">0.0102647</td>
<td align="right">38.0601753</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>315 Safety and quality inspectors</td>
<td align="right">-0.1200257</td>
<td align="right">0.0091762</td>
<td align="right">-13.0800884</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>321 Agronomy and forestry technicians</td>
<td align="right">-0.1451979</td>
<td align="right">0.0136048</td>
<td align="right">-10.6725322</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>322 Health associate professionals (except nursing)</td>
<td align="right">-0.1388401</td>
<td align="right">0.0088585</td>
<td align="right">-15.6730682</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>323 Nursing associate professionals</td>
<td align="right">-0.0797149</td>
<td align="right">0.0090905</td>
<td align="right">-8.7690673</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>324 Life science technicians</td>
<td align="right">-0.2069808</td>
<td align="right">0.0110118</td>
<td align="right">-18.7962311</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>331 Pre-primary education teaching associate professionals</td>
<td align="right">-0.3033610</td>
<td align="right">0.0099170</td>
<td align="right">-30.5901460</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>332 Other teaching associate professionals</td>
<td align="right">-0.2774992</td>
<td align="right">0.0128234</td>
<td align="right">-21.6400468</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>341 Finance and sales associate professionals</td>
<td align="right">-0.0239146</td>
<td align="right">0.0075566</td>
<td align="right">-3.1647205</td>
<td align="right">0.0015572</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>342 Business services agents and trade brokers</td>
<td align="right">-0.1491105</td>
<td align="right">0.0078277</td>
<td align="right">-19.0490038</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>343 Administrative associate professionals</td>
<td align="right">-0.1074541</td>
<td align="right">0.0075641</td>
<td align="right">-14.2058125</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>346 Social work associate professionals</td>
<td align="right">-0.3102289</td>
<td align="right">0.0080925</td>
<td align="right">-38.3352361</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>347 Artistic, entertainment and sports associate professionals</td>
<td align="right">-0.1286704</td>
<td align="right">0.0083758</td>
<td align="right">-15.3621676</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>411 Office secretaries and data entry operators</td>
<td align="right">-0.2446566</td>
<td align="right">0.0085685</td>
<td align="right">-28.5531838</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>412 Numerical clerks</td>
<td align="right">-0.2419657</td>
<td align="right">0.0075791</td>
<td align="right">-31.9252462</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>413 Stores and transport clerks</td>
<td align="right">-0.2638604</td>
<td align="right">0.0075790</td>
<td align="right">-34.8145586</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>415 Mail carriers and sorting clerks</td>
<td align="right">-0.4045545</td>
<td align="right">0.0097712</td>
<td align="right">-41.4026300</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>419 Other office clerks</td>
<td align="right">-0.2812810</td>
<td align="right">0.0075640</td>
<td align="right">-37.1865647</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>421 Cashiers, tellers and related clerks</td>
<td align="right">-0.2911851</td>
<td align="right">0.0085149</td>
<td align="right">-34.1973054</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>422 Client information clerks</td>
<td align="right">-0.3466551</td>
<td align="right">0.0076021</td>
<td align="right">-45.6000045</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>511 Travel attendants and related workers</td>
<td align="right">-0.1698378</td>
<td align="right">0.0080115</td>
<td align="right">-21.1992587</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>512 Housekeeping and restaurant services workers</td>
<td align="right">-0.3675951</td>
<td align="right">0.0112797</td>
<td align="right">-32.5890874</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>513 Personal care and related workers</td>
<td align="right">-0.3716465</td>
<td align="right">0.0075867</td>
<td align="right">-48.9868159</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>514 Other personal services workers</td>
<td align="right">-0.3457294</td>
<td align="right">0.0156694</td>
<td align="right">-22.0640010</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>515 Protective services workers</td>
<td align="right">-0.2028056</td>
<td align="right">0.0120050</td>
<td align="right">-16.8934447</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>522 Shop and stall salespersons and demonstrators</td>
<td align="right">-0.2671818</td>
<td align="right">0.0075790</td>
<td align="right">-35.2527597</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>712 Building frame and related trades workers</td>
<td align="right">-0.2663715</td>
<td align="right">0.0166078</td>
<td align="right">-16.0389248</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>713 Building finishers and related trades workers</td>
<td align="right">-0.2953711</td>
<td align="right">0.0112955</td>
<td align="right">-26.1493579</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>723 Machinery mechanics and fitters</td>
<td align="right">-0.2832357</td>
<td align="right">0.0105255</td>
<td align="right">-26.9095171</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>724 Electrical and electronic equipment mechanics and fitters</td>
<td align="right">-0.2433953</td>
<td align="right">0.0093842</td>
<td align="right">-25.9367630</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>734 Craft printing and related trades workers</td>
<td align="right">-0.2137465</td>
<td align="right">0.0180896</td>
<td align="right">-11.8159893</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>815 Chemical-processing-plant operators</td>
<td align="right">-0.1040442</td>
<td align="right">0.0425224</td>
<td align="right">-2.4468097</td>
<td align="right">0.0144308</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>816 Power-production and related plant operators</td>
<td align="right">-0.2126282</td>
<td align="right">0.0113508</td>
<td align="right">-18.7323998</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>825 Printing-, binding- and paper-products machine operators</td>
<td align="right">-0.1779737</td>
<td align="right">0.0240425</td>
<td align="right">-7.4024477</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>828 Assemblers</td>
<td align="right">-0.2745193</td>
<td align="right">0.0211832</td>
<td align="right">-12.9592743</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>829 Other machine operators and assemblers</td>
<td align="right">-0.1861654</td>
<td align="right">0.0224749</td>
<td align="right">-8.2832519</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>831 Locomotive-engine drivers and related worker</td>
<td align="right">-0.1837192</td>
<td align="right">0.0102368</td>
<td align="right">-17.9469107</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>832 Motor-vehicle drivers</td>
<td align="right">-0.4036730</td>
<td align="right">0.0092552</td>
<td align="right">-43.6156159</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>912 Helpers and cleaners</td>
<td align="right">-0.4112420</td>
<td align="right">0.0095967</td>
<td align="right">-42.8526533</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>913 Helpers in restaurants</td>
<td align="right">-0.4004462</td>
<td align="right">0.0272415</td>
<td align="right">-14.6998478</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>914 Doorkeepers, newspaper and package deliverers and related workers</td>
<td align="right">-0.4233767</td>
<td align="right">0.0112253</td>
<td align="right">-37.7163717</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occupational group (SSYK)</code>919 Other sales and services elementary occupations</td>
<td align="right">-0.4459274</td>
<td align="right">0.0147337</td>
<td align="right">-30.2659045</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code>933 Transport labourers and freight handlers</td>
<td align="right">-0.2855748</td>
<td align="right">0.0845382</td>
<td align="right">-3.3780563</td>
<td align="right">0.0007330</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">0.0295469</td>
<td align="right">0.0002218</td>
<td align="right">133.2286965</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">sexwomen</td>
<td align="right">-0.0940155</td>
<td align="right">0.0019313</td>
<td align="right">-48.6800444</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)1</td>
<td align="right">8.0085927</td>
<td align="right">0.0860976</td>
<td align="right">93.0176060</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)2</td>
<td align="right">-5.4012785</td>
<td align="right">0.0860881</td>
<td align="right">-62.7413239</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)3</td>
<td align="right">0.6344314</td>
<td align="right">0.0849507</td>
<td align="right">7.4682340</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb58-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb58-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb58-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb58-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_2)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>occupational group (SSYK)</code></td>
<td align="right">453.90944</td>
<td align="right">70</td>
<td align="right">912.2726</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">126.16594</td>
<td align="right">1</td>
<td align="right">17749.8856</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">16.84413</td>
<td align="right">1</td>
<td align="right">2369.7467</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)</td>
<td align="right">88.63996</td>
<td align="right">3</td>
<td align="right">4156.8249</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Residuals</td>
<td align="right">67.14914</td>
<td align="right">9447</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="ssyk-214-architects-engineers-and-related-professionals-year-2014---2018" class="section level2">
<h2><span class="header-section-number">9.9</span> SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018</h2>
<p>Average monthly pay, non-manual workers private sector (SLP) by occupational
group (SSYK 2012) age and sex. Year 2014 - 2018
Average monthly pay (total pay), non-manual workers private sector (SLP), SEK
by occupational group (SSYK), age, sex and year</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;00000031_1.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age4 =</span> (age3 <span class="op">+</span><span class="st"> </span>age2) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-7" title="7"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span>, age, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb59-8" title="8"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))  </a></code></pre></div>
<pre><code>## Warning: Grouping rowwise data frame strips rowwise nature</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">tb <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb61-2" title="2"><span class="st">  </span><span class="kw">ggplot</span> () <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb61-3" title="3"><span class="st">    </span><span class="kw">geom_point</span> (<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2,<span class="dt">y =</span> <span class="kw">log</span>(salary), <span class="dt">colour =</span> age, <span class="dt">shape=</span>sex))  </a></code></pre></div>
<div class="figure"><span id="fig:ssyk14-18"></span>
<img src="SCB-Engineers-Jonkoping_files/figure-html/ssyk14-18-1.png" alt="SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018" width="672" />
<p class="caption">
Figure 9.9: SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018
</p>
</div>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span><span class="kw">poly</span>(age4, <span class="dv">3</span>), <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb62-2" title="2"></a>
<a class="sourceLine" id="cb62-3" title="3">tb &lt;-<span class="st"> </span><span class="kw">bind_cols</span>(tb, <span class="kw">as_tibble</span>(<span class="kw">exp</span>(<span class="kw">predict</span>(model, tb, <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>))))</a></code></pre></div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">tb <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb63-2" title="2"><span class="st">  </span><span class="kw">ggplot</span> () <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb63-3" title="3"><span class="st">    </span><span class="kw">geom_point</span> (<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2,<span class="dt">y =</span> <span class="kw">log</span>(fit), <span class="dt">colour =</span> age, <span class="dt">shape=</span>sex))</a></code></pre></div>
<div class="figure">
<img src="SCB-Engineers-Jonkoping_files/figure-html/ssyk14-18_2-1.png" alt="Model fit, SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018" width="672" />
<p class="caption">
(#fig:ssyk14-18_2)Model fit, SSYK 214, Architects, engineers and related professionals, Year 2014 - 2018
</p>
</div>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb64-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb64-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_2)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-27.9987545</td>
<td align="right">4.1947424</td>
<td align="right">-6.674726</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">0.0191776</td>
<td align="right">0.0020807</td>
<td align="right">9.216871</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">sexwomen</td>
<td align="right">-0.0353468</td>
<td align="right">0.0059660</td>
<td align="right">-5.924684</td>
<td align="right">0.0000001</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)1</td>
<td align="right">1.5018782</td>
<td align="right">0.0286694</td>
<td align="right">52.386134</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)2</td>
<td align="right">-0.7321485</td>
<td align="right">0.0287026</td>
<td align="right">-25.508120</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)3</td>
<td align="right">0.0082994</td>
<td align="right">0.0287225</td>
<td align="right">0.288952</td>
<td align="right">0.7732977</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb65-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb65-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb65-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb65-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_2)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2</td>
<td align="right">0.0694613</td>
<td align="right">1</td>
<td align="right">84.95072</td>
<td align="right">0e+00</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0.0287016</td>
<td align="right">1</td>
<td align="right">35.10188</td>
<td align="right">1e-07</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)</td>
<td align="right">2.7897056</td>
<td align="right">3</td>
<td align="right">1137.26462</td>
<td align="right">0e+00</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">0.0719545</td>
<td align="right">88</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;00000031_3.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb66-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age4 =</span> (age3 <span class="op">+</span><span class="st"> </span>age2) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-7" title="7"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span>, age, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb66-8" title="8"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))</a></code></pre></div>
<pre><code>## Warning: Grouping rowwise data frame strips rowwise nature</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> `</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span> <span class="op">+</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span><span class="kw">poly</span>(age4, <span class="dv">3</span>), <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb68-2" title="2">    </a>
<a class="sourceLine" id="cb68-3" title="3"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb68-4" title="4"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb68-5" title="5"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb68-6" title="6">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb68-7" title="7">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_2)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-37.5468927</td>
<td align="right">2.0470713</td>
<td align="right">-18.3417615</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>112 Managing directors and chief executives</td>
<td align="right">0.6170543</td>
<td align="right">0.0192423</td>
<td align="right">32.0676708</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>121 Finance managers</td>
<td align="right">0.4769831</td>
<td align="right">0.0156019</td>
<td align="right">30.5721499</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>122 Human resource managers</td>
<td align="right">0.4542501</td>
<td align="right">0.0164617</td>
<td align="right">27.5943225</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>123 Administration and planning managers</td>
<td align="right">0.4956227</td>
<td align="right">0.0167515</td>
<td align="right">29.5867070</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>124 Information, communication and public relations managers</td>
<td align="right">0.5278895</td>
<td align="right">0.0246679</td>
<td align="right">21.3998755</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>125 Sales and marketing managers</td>
<td align="right">0.3861924</td>
<td align="right">0.0148564</td>
<td align="right">25.9950674</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>129 Administration and service managers not elsewhere classified</td>
<td align="right">0.2823372</td>
<td align="right">0.0148218</td>
<td align="right">19.0488006</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>131 Information and communications technology service managers</td>
<td align="right">0.4022867</td>
<td align="right">0.0158027</td>
<td align="right">25.4568486</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>132 Supply, logistics and transport managers</td>
<td align="right">0.2973659</td>
<td align="right">0.0166430</td>
<td align="right">17.8673640</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>133 Research and development managers</td>
<td align="right">0.5276822</td>
<td align="right">0.0161981</td>
<td align="right">32.5768948</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>134 Architectural and engineering managers</td>
<td align="right">0.3935430</td>
<td align="right">0.0161977</td>
<td align="right">24.2961723</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>135 Real estate and head of administration manager</td>
<td align="right">0.2313332</td>
<td align="right">0.0277684</td>
<td align="right">8.3308092</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>136 Production managers in construction and mining</td>
<td align="right">0.2887767</td>
<td align="right">0.0161857</td>
<td align="right">17.8415086</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>137 Production managers in manufacturing</td>
<td align="right">0.1975406</td>
<td align="right">0.0161121</td>
<td align="right">12.2604253</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>141 Primary and secondary schools and adult education managers</td>
<td align="right">0.1834401</td>
<td align="right">0.0890480</td>
<td align="right">2.0600138</td>
<td align="right">0.0394652</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>151 Health care managers</td>
<td align="right">0.1681348</td>
<td align="right">0.0188836</td>
<td align="right">8.9037297</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>154 Managers and leaders within religious bodies</td>
<td align="right">0.2966825</td>
<td align="right">0.0456125</td>
<td align="right">6.5044143</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>159 Other social services managers</td>
<td align="right">0.2081647</td>
<td align="right">0.0175764</td>
<td align="right">11.8434133</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>161 Financial and insurance managers</td>
<td align="right">0.7252319</td>
<td align="right">0.0165534</td>
<td align="right">43.8115622</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>172 Restaurant managers</td>
<td align="right">-0.0518488</td>
<td align="right">0.0230186</td>
<td align="right">-2.2524718</td>
<td align="right">0.0243494</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>173 Retail and wholesale trade managers</td>
<td align="right">0.1104125</td>
<td align="right">0.0175625</td>
<td align="right">6.2868269</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>179 Other services managers not elsewhere classified</td>
<td align="right">0.0896892</td>
<td align="right">0.0151243</td>
<td align="right">5.9301557</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>211 Physicists and chemists</td>
<td align="right">0.1497958</td>
<td align="right">0.0157317</td>
<td align="right">9.5218952</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>212 Mathematicians, actuaries and statisticians</td>
<td align="right">0.1949668</td>
<td align="right">0.0890529</td>
<td align="right">2.1893368</td>
<td align="right">0.0286330</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>213 Biologists, pharmacologists and specialists in agriculture and forestry</td>
<td align="right">0.0421748</td>
<td align="right">0.0159456</td>
<td align="right">2.6449250</td>
<td align="right">0.0082046</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>214 Engineering professionals</td>
<td align="right">0.1572491</td>
<td align="right">0.0141277</td>
<td align="right">11.1305556</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>216 Architects and surveyors</td>
<td align="right">0.0515622</td>
<td align="right">0.0173139</td>
<td align="right">2.9780763</td>
<td align="right">0.0029190</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>217 Designers</td>
<td align="right">-0.0081672</td>
<td align="right">0.0154654</td>
<td align="right">-0.5280988</td>
<td align="right">0.5974617</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>218 Specialists within environmental and health protection</td>
<td align="right">0.0740458</td>
<td align="right">0.0173017</td>
<td align="right">4.2796822</td>
<td align="right">0.0000192</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>221 Medical doctors</td>
<td align="right">0.5403667</td>
<td align="right">0.0166303</td>
<td align="right">32.4928738</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>222 Nursing professionals</td>
<td align="right">0.0609359</td>
<td align="right">0.0146890</td>
<td align="right">4.1484062</td>
<td align="right">0.0000342</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>223 Nursing professionals (cont.)</td>
<td align="right">-0.0375099</td>
<td align="right">0.0185202</td>
<td align="right">-2.0253518</td>
<td align="right">0.0429011</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>224 Psychologists and psychotherapists</td>
<td align="right">0.1310728</td>
<td align="right">0.0634630</td>
<td align="right">2.0653411</td>
<td align="right">0.0389585</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>225 Veterinarians</td>
<td align="right">0.1451057</td>
<td align="right">0.0246877</td>
<td align="right">5.8776629</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>226 Dentists</td>
<td align="right">0.2061785</td>
<td align="right">0.0217913</td>
<td align="right">9.4614837</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>227 Naprapaths, physiotherapists, occupational therapists</td>
<td align="right">-0.1370381</td>
<td align="right">0.0177376</td>
<td align="right">-7.7258431</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>228 Specialists in health care not elsewhere classified</td>
<td align="right">0.0071140</td>
<td align="right">0.0168624</td>
<td align="right">0.4218871</td>
<td align="right">0.6731313</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>231 University and higher education teachers</td>
<td align="right">0.1367054</td>
<td align="right">0.0160981</td>
<td align="right">8.4920376</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>232 Vocational education teachers</td>
<td align="right">-0.2934218</td>
<td align="right">0.0634613</td>
<td align="right">-4.6236362</td>
<td align="right">0.0000039</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>233 Secondary education teachers</td>
<td align="right">-0.1041122</td>
<td align="right">0.0351897</td>
<td align="right">-2.9586030</td>
<td align="right">0.0031095</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>234 Primary- and pre-school teachers</td>
<td align="right">-0.1872326</td>
<td align="right">0.0143234</td>
<td align="right">-13.0717619</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>235 Teaching professionals not elsewhere classified</td>
<td align="right">-0.1425854</td>
<td align="right">0.0168496</td>
<td align="right">-8.4622613</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>241 Accountants, financial analysts and fund managers</td>
<td align="right">0.2278752</td>
<td align="right">0.0144328</td>
<td align="right">15.7887542</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>242 Organisation analysts, policy administrators and human resource specialists</td>
<td align="right">0.1696041</td>
<td align="right">0.0142889</td>
<td align="right">11.8696265</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>243 Marketing and public relations professionals</td>
<td align="right">0.1407585</td>
<td align="right">0.0144341</td>
<td align="right">9.7518221</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>251 ICT architects, systems analysts and test managers</td>
<td align="right">0.1672958</td>
<td align="right">0.0140985</td>
<td align="right">11.8662120</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>261 Legal professionals</td>
<td align="right">0.3910677</td>
<td align="right">0.0155923</td>
<td align="right">25.0808377</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>264 Authors, journalists and linguists</td>
<td align="right">-0.0018197</td>
<td align="right">0.0142888</td>
<td align="right">-0.1273494</td>
<td align="right">0.8986706</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>265 Creative and performing artists</td>
<td align="right">-0.0880117</td>
<td align="right">0.0149099</td>
<td align="right">-5.9029016</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>266 Social work and counselling professionals</td>
<td align="right">-0.0295346</td>
<td align="right">0.0205064</td>
<td align="right">-1.4402594</td>
<td align="right">0.1498765</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>267 Religious professionals and deacons</td>
<td align="right">-0.0405199</td>
<td align="right">0.0173192</td>
<td align="right">-2.3395977</td>
<td align="right">0.0193561</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>311 Physical and engineering science technicians</td>
<td align="right">0.0168089</td>
<td align="right">0.0141598</td>
<td align="right">1.1870890</td>
<td align="right">0.2352668</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>312 Construction and manufacturing supervisors</td>
<td align="right">-0.0106277</td>
<td align="right">0.0149022</td>
<td align="right">-0.7131646</td>
<td align="right">0.4757877</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>315 Ship and aircraft controllers and technicians</td>
<td align="right">0.2331542</td>
<td align="right">0.0192622</td>
<td align="right">12.1042123</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>321 Medical and pharmaceutical technicians</td>
<td align="right">-0.0730238</td>
<td align="right">0.0143600</td>
<td align="right">-5.0852059</td>
<td align="right">0.0000004</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>324 Veterinary assistants</td>
<td align="right">-0.1810371</td>
<td align="right">0.0205006</td>
<td align="right">-8.8308107</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>325 Dental hygienists</td>
<td align="right">-0.1573366</td>
<td align="right">0.0177376</td>
<td align="right">-8.8702166</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>331 Financial and accounting associate professionals</td>
<td align="right">0.0449942</td>
<td align="right">0.0142214</td>
<td align="right">3.1638300</td>
<td align="right">0.0015694</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>332 Insurance advisers, sales and purchasing agents</td>
<td align="right">0.0509263</td>
<td align="right">0.0141278</td>
<td align="right">3.6046962</td>
<td align="right">0.0003165</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>333 Business services agents</td>
<td align="right">-0.0320470</td>
<td align="right">0.0145514</td>
<td align="right">-2.2023342</td>
<td align="right">0.0277016</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>334 Administrative and specialized secretaries</td>
<td align="right">-0.0007863</td>
<td align="right">0.0147644</td>
<td align="right">-0.0532548</td>
<td align="right">0.9575317</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>335 Tax and related government associate professionals</td>
<td align="right">-0.0126953</td>
<td align="right">0.0145522</td>
<td align="right">-0.8723958</td>
<td align="right">0.3830477</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>341 Social work and religious associate professionals</td>
<td align="right">-0.2183480</td>
<td align="right">0.0166441</td>
<td align="right">-13.1186498</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>342 Athletes, fitness instructors and recreational workers</td>
<td align="right">-0.1492056</td>
<td align="right">0.0147206</td>
<td align="right">-10.1358383</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>343 Photographers, interior decorators and entertainers</td>
<td align="right">-0.1203248</td>
<td align="right">0.0162674</td>
<td align="right">-7.3966895</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>344 Driving instructors and other instructors</td>
<td align="right">-0.2170414</td>
<td align="right">0.0277391</td>
<td align="right">-7.8243728</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>345 Culinary associate professionals</td>
<td align="right">-0.3831146</td>
<td align="right">0.0278107</td>
<td align="right">-13.7757851</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>351 ICT operations and user support technicians</td>
<td align="right">-0.0335916</td>
<td align="right">0.0142884</td>
<td align="right">-2.3509619</td>
<td align="right">0.0187758</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>352 Broadcasting and audio-visual technicians</td>
<td align="right">-0.2179292</td>
<td align="right">0.0190592</td>
<td align="right">-11.4343596</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>411 Office assistants and other secretaries</td>
<td align="right">-0.1911902</td>
<td align="right">0.0141285</td>
<td align="right">-13.5322664</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>422 Client information clerks</td>
<td align="right">-0.2841125</td>
<td align="right">0.0141584</td>
<td align="right">-20.0666661</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code>511 Cabin crew, guides and related workers</td>
<td align="right">-0.1823307</td>
<td align="right">0.0183293</td>
<td align="right">-9.9474824</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left"><code>occuptional  (SSYK 2012)</code>524 Event seller and telemarketers</td>
<td align="right">-0.2089114</td>
<td align="right">0.0195200</td>
<td align="right">-10.7024445</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">year2</td>
<td align="right">0.0238570</td>
<td align="right">0.0010154</td>
<td align="right">23.4955442</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">sexwomen</td>
<td align="right">-0.0767252</td>
<td align="right">0.0030556</td>
<td align="right">-25.1096548</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)1</td>
<td align="right">6.6940905</td>
<td align="right">0.0918162</td>
<td align="right">72.9074788</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)2</td>
<td align="right">-4.1563876</td>
<td align="right">0.0920040</td>
<td align="right">-45.1761784</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">poly(age4, 3)3</td>
<td align="right">0.2201252</td>
<td align="right">0.0896214</td>
<td align="right">2.4561686</td>
<td align="right">0.0140872</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb69-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb69-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>)  </a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_2)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>occuptional  (SSYK 2012)</code></td>
<td align="right">180.651642</td>
<td align="right">73</td>
<td align="right">317.1308</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">4.307761</td>
<td align="right">1</td>
<td align="right">552.0406</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">4.919966</td>
<td align="right">1</td>
<td align="right">630.4948</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">poly(age4, 3)</td>
<td align="right">56.139659</td>
<td align="right">3</td>
<td align="right">2398.1033</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Residuals</td>
<td align="right">29.629289</td>
<td align="right">3797</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="ssyk-214-architects-engineers-and-related-professionals-by-region-year-2000---2018" class="section level2">
<h2><span class="header-section-number">9.10</span> SSYK 214, Architects, engineers and related professionals by region, Year 2000 - 2018</h2>
<p>Average monthly pay, non-manual workers private sector (SLP) by region,
occupational group (SSYK) and sex. Year 2000 - 2013
Average monthly pay (total pay), non-manual workers private sector (SLP)
214 Engineering professionals</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103H2_4.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb70-2" title="2"><span class="st">    </span><span class="kw">filter</span>(year2 <span class="op">&gt;</span><span class="st"> </span><span class="dv">1994</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb70-3" title="3"><span class="st">    </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occupational group (SSYK)</span><span class="st">`</span>, region, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb70-4" title="4"><span class="st">    </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))</a>
<a class="sourceLine" id="cb70-5" title="5"></a>
<a class="sourceLine" id="cb70-6" title="6">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>region <span class="op">+</span><span class="st"> </span>sex, <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb70-7" title="7">    </a>
<a class="sourceLine" id="cb70-8" title="8"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb70-9" title="9"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb70-10" title="10"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb70-11" title="11">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb70-12" title="12">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_3)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-46.0930565</td>
<td align="right">1.0429843</td>
<td align="right">-44.193433</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">0.0282072</td>
<td align="right">0.0005198</td>
<td align="right">54.261845</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">regionSE11 Stockholm</td>
<td align="right">0.0703349</td>
<td align="right">0.0086749</td>
<td align="right">8.107902</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">regionSE12 East-Central Sweden</td>
<td align="right">-0.0157809</td>
<td align="right">0.0086749</td>
<td align="right">-1.819154</td>
<td align="right">0.0701715</td>
</tr>
<tr class="odd">
<td align="left">regionSE21 Småland and islands</td>
<td align="right">-0.1108373</td>
<td align="right">0.0087553</td>
<td align="right">-12.659461</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">regionSE22 South Sweden</td>
<td align="right">-0.0267388</td>
<td align="right">0.0086749</td>
<td align="right">-3.082338</td>
<td align="right">0.0023012</td>
</tr>
<tr class="odd">
<td align="left">regionSE23 West Sweden</td>
<td align="right">-0.0314878</td>
<td align="right">0.0086749</td>
<td align="right">-3.629783</td>
<td align="right">0.0003487</td>
</tr>
<tr class="even">
<td align="left">regionSE31 North-Central Sweden</td>
<td align="right">-0.0709119</td>
<td align="right">0.0086749</td>
<td align="right">-8.174426</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">regionSE32 Central Norrland</td>
<td align="right">-0.0526836</td>
<td align="right">0.0090429</td>
<td align="right">-5.825939</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">regionSE33 Upper Norrland</td>
<td align="right">-0.0949739</td>
<td align="right">0.0089418</td>
<td align="right">-10.621353</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">sexwomen</td>
<td align="right">-0.0997849</td>
<td align="right">0.0041684</td>
<td align="right">-23.938280</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb71-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb71-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<table>
<caption>(#tab:ssyk00-13_3)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2</td>
<td align="right">3.1019977</td>
<td align="right">1</td>
<td align="right">2944.34786</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">region</td>
<td align="right">0.6452772</td>
<td align="right">8</td>
<td align="right">76.56036</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">0.6037237</td>
<td align="right">1</td>
<td align="right">573.04126</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">0.2454756</td>
<td align="right">233</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>Average monthly pay, non-manual workers private sector (SLP) by region,
occupational group (SSYK 2012) and sex. Year 2014 - 2018
Average monthly pay (total pay), non-manual workers private sector (SLP)
214 Engineering professionals</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;0000002T_1.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb72-2" title="2"><span class="st">    </span><span class="kw">filter</span>(year2 <span class="op">&gt;</span><span class="st"> </span><span class="dv">1994</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb72-3" title="3"><span class="st">    </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">occuptional  (SSYK 2012)</span><span class="st">`</span>, region, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb72-4" title="4"><span class="st">    </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))</a>
<a class="sourceLine" id="cb72-5" title="5"></a>
<a class="sourceLine" id="cb72-6" title="6">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> </span>year2 <span class="op">+</span><span class="st"> </span>region <span class="op">+</span><span class="st"> </span>sex, <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb72-7" title="7">    </a>
<a class="sourceLine" id="cb72-8" title="8"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb72-9" title="9"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb72-10" title="10"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb72-11" title="11">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb72-12" title="12">  <span class="dt">caption =</span> <span class="st">&#39;Summary from linear model fit&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_3)Summary from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-28.1357687</td>
<td align="right">3.8206133</td>
<td align="right">-7.364202</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">year2</td>
<td align="right">0.0192890</td>
<td align="right">0.0018951</td>
<td align="right">10.178127</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">regionSE12 East-Central Sweden</td>
<td align="right">-0.0564776</td>
<td align="right">0.0107205</td>
<td align="right">-5.268172</td>
<td align="right">1.40e-06</td>
</tr>
<tr class="even">
<td align="left">regionSE21 Småland and islands</td>
<td align="right">-0.1296477</td>
<td align="right">0.0107205</td>
<td align="right">-12.093398</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">regionSE22 South Sweden</td>
<td align="right">-0.0453027</td>
<td align="right">0.0107205</td>
<td align="right">-4.225790</td>
<td align="right">7.06e-05</td>
</tr>
<tr class="even">
<td align="left">regionSE23 West Sweden</td>
<td align="right">-0.0511164</td>
<td align="right">0.0107205</td>
<td align="right">-4.768079</td>
<td align="right">9.80e-06</td>
</tr>
<tr class="odd">
<td align="left">regionSE31 North-Central Sweden</td>
<td align="right">-0.0979477</td>
<td align="right">0.0107205</td>
<td align="right">-9.136453</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">regionSE32 Central Norrland</td>
<td align="right">-0.1136594</td>
<td align="right">0.0107205</td>
<td align="right">-10.602028</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">regionSE33 Upper Norrland</td>
<td align="right">-0.1411647</td>
<td align="right">0.0107205</td>
<td align="right">-13.167691</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">sexwomen</td>
<td align="right">-0.0590904</td>
<td align="right">0.0053603</td>
<td align="right">-11.023773</td>
<td align="right">0.00e+00</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb73-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb73-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb73-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb73-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_3)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2</td>
<td align="right">0.0595304</td>
<td align="right">1</td>
<td align="right">103.59427</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">region</td>
<td align="right">0.1664982</td>
<td align="right">7</td>
<td align="right">41.39124</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">0.0698335</td>
<td align="right">1</td>
<td align="right">121.52358</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">0.0402255</td>
<td align="right">70</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="level-of-education-ssyk-214-architects-engineers-and-related-professionals" class="section level2">
<h2><span class="header-section-number">9.11</span> Level of education , SSYK 214, Architects, engineers and related professionals</h2>
<p>Average basic salary, monthly salary and women´s salary as a percentage of
men´s salary by sector, occupational group (SSYK 2012), sex and educational
level (SUN). Year 2014 - 2018
Monthly salary
5 non-manual workers private sector
214 Engineering professionals</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000CY.csv&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb74-2" title="2"><span class="st">    </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">level of education</span><span class="st">`</span>, sex) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb74-3" title="3"><span class="st">    </span><span class="kw">mutate</span> (<span class="dt">grouprelsal =</span> <span class="kw">relative_dev</span> (salary))</a>
<a class="sourceLine" id="cb74-4" title="4"></a>
<a class="sourceLine" id="cb74-5" title="5">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary) <span class="op">~</span><span class="st"> `</span><span class="dt">level of education</span><span class="st">`</span> <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>year2, <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb74-6" title="6">    </a>
<a class="sourceLine" id="cb74-7" title="7"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb74-8" title="8"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb74-9" title="9"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb74-10" title="10">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb74-11" title="11">  <span class="dt">caption =</span> <span class="st">&#39;Level of education for SSYK 214&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_4)Level of education for SSYK 214</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-23.8760678</td>
<td align="right">7.0878306</td>
<td align="right">-3.3686002</td>
<td align="right">0.0013476</td>
</tr>
<tr class="even">
<td align="left"><code>level of education</code>post-graduate education (ISCED97 6)</td>
<td align="right">0.1123593</td>
<td align="right">0.0179837</td>
<td align="right">6.2478322</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left"><code>level of education</code>post-secondary education 3 years or more (ISCED97 5A)</td>
<td align="right">-0.0049891</td>
<td align="right">0.0179837</td>
<td align="right">-0.2774206</td>
<td align="right">0.7824436</td>
</tr>
<tr class="even">
<td align="left"><code>level of education</code>post-secondary education, less than 3 years (ISCED97 4+5B)</td>
<td align="right">-0.0408825</td>
<td align="right">0.0179837</td>
<td align="right">-2.2733079</td>
<td align="right">0.0267275</td>
</tr>
<tr class="odd">
<td align="left"><code>level of education</code>primary and secondary education 9-10 years (ISCED97 2)</td>
<td align="right">-0.1207083</td>
<td align="right">0.0199380</td>
<td align="right">-6.0541888</td>
<td align="right">0.0000001</td>
</tr>
<tr class="even">
<td align="left"><code>level of education</code>upper secondary education 3 years (ISCED97 3A)</td>
<td align="right">-0.0850009</td>
<td align="right">0.0179837</td>
<td align="right">-4.7265479</td>
<td align="right">0.0000150</td>
</tr>
<tr class="odd">
<td align="left"><code>level of education</code>upper secondary education, 2 years or less (ISCED97 3C)</td>
<td align="right">-0.1108685</td>
<td align="right">0.0179837</td>
<td align="right">-6.1649398</td>
<td align="right">0.0000001</td>
</tr>
<tr class="even">
<td align="left">sexwomen</td>
<td align="right">-0.0854343</td>
<td align="right">0.0099224</td>
<td align="right">-8.6102526</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">year2</td>
<td align="right">0.0171685</td>
<td align="right">0.0035157</td>
<td align="right">4.8833120</td>
<td align="right">0.0000086</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb75-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb75-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb75-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb75-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_4)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>level of education</code></td>
<td align="right">0.3709710</td>
<td align="right">6</td>
<td align="right">38.23488</td>
<td align="right">0.0e+00</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0.1198839</td>
<td align="right">1</td>
<td align="right">74.13645</td>
<td align="right">0.0e+00</td>
</tr>
<tr class="odd">
<td align="left">year2</td>
<td align="right">0.0385619</td>
<td align="right">1</td>
<td align="right">23.84674</td>
<td align="right">8.6e-06</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">0.0937901</td>
<td align="right">58</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2014---2018" class="section level2">
<h2><span class="header-section-number">9.12</span> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2014 - 2018</h2>
<p>Average basic salary, monthly salary and women´s salary as a percentage of men´s salary by region, sector, occupational group (SSYK 2012) and sex . Year 2014 - 2018
Monthly salaty
All sectors
214 Engineering professionals</p>
<p>Average basic salary, monthly salary and women´s salary as a percentage of men´s salary by region, sector, occupational group (SSYK 2012) and sex . Year 2014 - 2018
Number of employees
All sectors
214 Engineering professionals</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000CG_10.csv&quot;</span>)</a>
<a class="sourceLine" id="cb76-2" title="2">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;000000CD_10.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb76-3" title="3"><span class="st">  </span><span class="kw">left_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb76-4" title="4"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb76-5" title="5"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary.x))))</a>
<a class="sourceLine" id="cb76-6" title="6">  </a>
<a class="sourceLine" id="cb76-7" title="7">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary.y) <span class="op">~</span><span class="st"> </span>year2.x <span class="op">+</span><span class="st"> </span>perc_women, <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb76-8" title="8">    </a>
<a class="sourceLine" id="cb76-9" title="9"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb76-10" title="10"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb76-11" title="11"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb76-12" title="12">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb76-13" title="13">  <span class="dt">caption =</span> <span class="st">&#39;The correlation between the proportion of engineers who are women and the salaries of engineers in the region.&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_5)The correlation between the proportion of engineers who are women and the salaries of engineers in the region.</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-16.8472433</td>
<td align="right">7.9797518</td>
<td align="right">-2.111249</td>
<td align="right">0.0381752</td>
</tr>
<tr class="even">
<td align="left">year2.x</td>
<td align="right">0.0135156</td>
<td align="right">0.0039623</td>
<td align="right">3.411042</td>
<td align="right">0.0010580</td>
</tr>
<tr class="odd">
<td align="left">perc_women</td>
<td align="right">0.0120174</td>
<td align="right">0.0018213</td>
<td align="right">6.598323</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb77-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb77-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb77-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb77-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_5)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">0.0249689</td>
<td align="right">1</td>
<td align="right">11.63521</td>
<td align="right">0.001058</td>
</tr>
<tr class="even">
<td align="left">perc_women</td>
<td align="right">0.0934314</td>
<td align="right">1</td>
<td align="right">43.53787</td>
<td align="right">0.000000</td>
</tr>
<tr class="odd">
<td align="left">Residuals</td>
<td align="right">0.1566566</td>
<td align="right">73</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="the-correlation-between-the-proportion-of-engineers-who-are-women-and-the-salaries-of-engineers-in-the-region.-year-2003---2013" class="section level2">
<h2><span class="header-section-number">9.13</span> The correlation between the proportion of engineers who are women and the salaries of engineers in the region. Year 2003 - 2013</h2>
<p>Average basic salary, monthly salary and women´s salary as a percentage of men´s salary by region, sector, occupational group (SSYK 2012) and sex . Year 2003 - 2013
Number of employees
All sectors
214 Engineering professionals</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0110A2.csv&quot;</span>)</a>
<a class="sourceLine" id="cb78-2" title="2">tb &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0110A4.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb78-3" title="3"><span class="st">  </span><span class="kw">left_join</span>(tb, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;region&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb78-4" title="4"><span class="st">  </span><span class="kw">group_by</span> (<span class="st">`</span><span class="dt">region</span><span class="st">`</span>, year) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb78-5" title="5"><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">perc_women =</span> <span class="kw">as.numeric</span> (<span class="kw">sub</span> (<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="kw">perc_women</span> (salary.x))))</a>
<a class="sourceLine" id="cb78-6" title="6">  </a>
<a class="sourceLine" id="cb78-7" title="7">model &lt;-<span class="st"> </span><span class="kw">lm</span> (<span class="kw">log</span>(salary.y) <span class="op">~</span><span class="st"> </span>year2.x <span class="op">+</span><span class="st"> </span>perc_women, <span class="dt">data =</span> tb)</a>
<a class="sourceLine" id="cb78-8" title="8">    </a>
<a class="sourceLine" id="cb78-9" title="9"><span class="kw">summary</span>(model) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb78-10" title="10"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb78-11" title="11"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb78-12" title="12">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb78-13" title="13">  <span class="dt">caption =</span> <span class="st">&#39;The correlation between the proportion of engineers who are women and the salaries of engineers in the region.&#39;</span>)</a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_6)The correlation between the proportion of engineers who are women and the salaries of engineers in the region.</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-30.8708500</td>
<td align="right">4.2567427</td>
<td align="right">-7.252224</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">year2.x</td>
<td align="right">0.0204578</td>
<td align="right">0.0021284</td>
<td align="right">9.611658</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">perc_women</td>
<td align="right">0.0120317</td>
<td align="right">0.0018553</td>
<td align="right">6.485125</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">Anova</span>(model, <span class="dt">type=</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb79-2" title="2"><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb79-3" title="3"><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>( </a>
<a class="sourceLine" id="cb79-4" title="4">  <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb79-5" title="5">  <span class="dt">caption =</span> <span class="st">&#39;Anova report from linear model fit&#39;</span>) </a></code></pre></div>
<table>
<caption>(#tab:ssyk14-18_6)Anova report from linear model fit</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">sumsq</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year2.x</td>
<td align="right">0.4587383</td>
<td align="right">1</td>
<td align="right">92.38397</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">perc_women</td>
<td align="right">0.2088358</td>
<td align="right">1</td>
<td align="right">42.05684</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Residuals</td>
<td align="right">0.7299375</td>
<td align="right">147</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="animations-ssyk-214-architects-engineers-and-related-professionals" class="section level2">
<h2><span class="header-section-number">9.14</span> Animations , SSYK 214, Architects, engineers and related professionals</h2>
<p>Approximaton with B-spline<br />
Average monthly pay (total pay), non-manual workers private sector (SLP),<br />
SEK by occuptional group (SSYK), age, sex and year 2000-2013<br />
214 Engineering professionals<br />
sex=total</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb80-3" title="3"><span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2 <span class="op">-</span><span class="st"> </span>(age2 <span class="op">+</span><span class="st"> </span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">y =</span> salary)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-4" title="4"><span class="st">   </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">   </span></a>
<a class="sourceLine" id="cb80-5" title="5"><span class="st">   </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>splines<span class="op">::</span><span class="kw">bs</span>(x, <span class="dv">8</span>), <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-6" title="6"><span class="st">   </span><span class="kw">transition_time</span>(year2) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-7" title="7"><span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year: {frame_time}&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-8" title="8"><span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Year of birth&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb80-9" title="9"><span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Salary&quot;</span>)  </a>
<a class="sourceLine" id="cb80-10" title="10"><span class="kw">anim_save</span>(<span class="st">&quot;2000-2013.gif&quot;</span>, <span class="dt">width =</span> <span class="dv">1000</span>, <span class="dt">height =</span> <span class="dv">1000</span>)   </a></code></pre></div>
<p><img src="https://mikaellundqvist.github.io/SCB-Engineers-Jonkoping/SCB-Engineers-Jonkoping_files/figure-html/2000-2013.gif" /></p>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP),<br />
SEK by occuptional (SSYK 2012), age, sex and year 2014-2018<br />
214 Engineering professionals<br />
sex=total</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">readfile</span>(<span class="st">&quot;00000031_2.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb81-3" title="3"><span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> year2 <span class="op">-</span><span class="st"> </span>(age2 <span class="op">+</span><span class="st"> </span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">y =</span> salary)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-4" title="4"><span class="st">   </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">   </span></a>
<a class="sourceLine" id="cb81-5" title="5"><span class="st">   </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>splines<span class="op">::</span><span class="kw">bs</span>(x, <span class="dv">8</span>), <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-6" title="6"><span class="st">   </span><span class="kw">transition_time</span>(year2) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-7" title="7"><span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year: {frame_time}&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-8" title="8"><span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Year of birth&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb81-9" title="9"><span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Salary&quot;</span>)    </a>
<a class="sourceLine" id="cb81-10" title="10"><span class="kw">anim_save</span>(<span class="st">&quot;2014-2018.gif&quot;</span>, <span class="dt">width =</span> <span class="dv">1000</span>, <span class="dt">height =</span> <span class="dv">1000</span>)    </a></code></pre></div>
<p><img src="https://mikaellundqvist.github.io/SCB-Engineers-Jonkoping/SCB-Engineers-Jonkoping_files/figure-html/2014-2018.gif" /></p>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP),<br />
SEK by occuptional (SSYK 2012), age, sex and year 2000-2013<br />
214 Engineering professionals<br />
sex=total<br />
Growth of salaries by age group</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">csvfile &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb82-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>])    </a>
<a class="sourceLine" id="cb82-5" title="5">yearwise &lt;-<span class="st"> </span><span class="kw">group_split</span>(csvfile <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(year2))      </a>
<a class="sourceLine" id="cb82-6" title="6">ageGroupGrowth =<span class="st"> </span><span class="kw">data.frame</span>()     </a>
<a class="sourceLine" id="cb82-7" title="7"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">13</span>){  </a>
<a class="sourceLine" id="cb82-8" title="8">  temp &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="dt">year =</span> <span class="dv">1999</span> <span class="op">+</span><span class="st"> </span>i, <span class="dt">age =</span> (yearwise[[i]]<span class="op">$</span>age2 <span class="op">+</span><span class="st"> </span>yearwise[[i]]<span class="op">$</span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">growth =</span> yearwise[[i<span class="op">+</span><span class="dv">1</span>]]<span class="op">$</span>relsalary <span class="op">/</span><span class="st"> </span>yearwise[[i]]<span class="op">$</span>relsalary) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>  </a>
<a class="sourceLine" id="cb82-9" title="9">  ageGroupGrowth &lt;-<span class="st"> </span><span class="kw">rbind</span>(ageGroupGrowth, temp)  </a>
<a class="sourceLine" id="cb82-10" title="10">}     </a>
<a class="sourceLine" id="cb82-11" title="11">ageGroupGrowth[, <span class="st">&#39;age&#39;</span>] &lt;-<span class="st"> </span><span class="kw">factor</span>(ageGroupGrowth[, <span class="st">&#39;age&#39;</span>])        </a>
<a class="sourceLine" id="cb82-12" title="12">ageGroupGrowth <span class="op">%&gt;%</span><span class="st">    </span></a>
<a class="sourceLine" id="cb82-13" title="13"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> growth)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-14" title="14"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-15" title="15"><span class="st">  </span><span class="kw">transition_time</span>(<span class="kw">as.numeric</span>(year)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-16" title="16"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year: {frame_time}&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-17" title="17"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Age group&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb82-18" title="18"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Salary increase (%)&quot;</span>)    </a>
<a class="sourceLine" id="cb82-19" title="19"><span class="kw">anim_save</span>(<span class="st">&quot;AgeGroupGrowth2000-2013.gif&quot;</span>, <span class="dt">width =</span> <span class="dv">1000</span>, <span class="dt">height =</span> <span class="dv">1000</span>)    </a></code></pre></div>
<p><img src="https://mikaellundqvist.github.io/SCB-Engineers-Jonkoping/SCB-Engineers-Jonkoping_files/figure-html/AgeGroupGrowth2000-2013.gif" /></p>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP),<br />
SEK by occuptional (SSYK 2012), age, sex and year 2000-2013<br />
214 Engineering professionals<br />
sex=total<br />
Individual salary increase by birthyear, estimated from B-spline approximation</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1">csvfile &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb83-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb83-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>])  </a>
<a class="sourceLine" id="cb83-5" title="5">indGrowth =<span class="st"> </span><span class="kw">data.frame</span>()  </a>
<a class="sourceLine" id="cb83-6" title="6"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2000</span><span class="op">:</span><span class="dv">2012</span>){  </a>
<a class="sourceLine" id="cb83-7" title="7">  yearfile &lt;-<span class="st"> </span><span class="kw">filter</span>(csvfile, year2 <span class="op">==</span><span class="st"> </span>i)  </a>
<a class="sourceLine" id="cb83-8" title="8">  x =<span class="st"> </span>yearfile<span class="op">$</span>year2 <span class="op">-</span><span class="st"> </span>(yearfile<span class="op">$</span>age2 <span class="op">+</span><span class="st"> </span>yearfile<span class="op">$</span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>  </a>
<a class="sourceLine" id="cb83-9" title="9">  model =<span class="st"> </span><span class="kw">lm</span>(yearfile<span class="op">$</span>salary <span class="op">~</span><span class="st"> </span>splines<span class="op">::</span><span class="kw">bs</span>(x, <span class="dv">8</span>))  </a>
<a class="sourceLine" id="cb83-10" title="10">  X1 =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span> <span class="kw">unlist</span>(<span class="kw">map2</span>( i <span class="op">-</span><span class="st"> </span><span class="dv">62</span>, i <span class="op">-</span><span class="st"> </span><span class="dv">22</span>, seq)))  </a>
<a class="sourceLine" id="cb83-11" title="11">  Y1 =<span class="st"> </span><span class="kw">predict</span>(model, X1)   </a>
<a class="sourceLine" id="cb83-12" title="12">  yearfile &lt;-<span class="st"> </span><span class="kw">filter</span>(csvfile, year2 <span class="op">==</span><span class="st"> </span>i <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)  </a>
<a class="sourceLine" id="cb83-13" title="13">  x =<span class="st"> </span>yearfile<span class="op">$</span>year2 <span class="op">-</span><span class="st"> </span>(yearfile<span class="op">$</span>age2 <span class="op">+</span><span class="st"> </span>yearfile<span class="op">$</span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>  </a>
<a class="sourceLine" id="cb83-14" title="14">  model =<span class="st"> </span><span class="kw">lm</span>(yearfile<span class="op">$</span>salary <span class="op">~</span><span class="st"> </span>splines<span class="op">::</span><span class="kw">bs</span>(x, <span class="dv">8</span>))  </a>
<a class="sourceLine" id="cb83-15" title="15">  X2 =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span> <span class="kw">unlist</span>(<span class="kw">map2</span>( i <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">62</span>, i <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">22</span>, seq)))      </a>
<a class="sourceLine" id="cb83-16" title="16">  Y2 =<span class="st"> </span><span class="kw">predict</span>(model, X2)  </a>
<a class="sourceLine" id="cb83-17" title="17">  growth =<span class="st"> </span>Y2[<span class="dv">1</span><span class="op">:</span><span class="dv">40</span>] <span class="op">/</span><span class="st"> </span>Y1[<span class="dv">2</span><span class="op">:</span><span class="dv">41</span>]    </a>
<a class="sourceLine" id="cb83-18" title="18">  temp &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(<span class="dt">year =</span> i<span class="op">+</span><span class="dv">1</span>, <span class="dt">by=</span>X2[<span class="dv">1</span><span class="op">:</span><span class="dv">40</span>,<span class="dv">1</span>], <span class="dt">growth=</span>growth))  </a>
<a class="sourceLine" id="cb83-19" title="19">  indGrowth &lt;-<span class="st"> </span><span class="kw">rbind</span>(indGrowth, temp)  </a>
<a class="sourceLine" id="cb83-20" title="20">}   </a>
<a class="sourceLine" id="cb83-21" title="21">indGrowth <span class="op">%&gt;%</span><span class="st">     </span></a>
<a class="sourceLine" id="cb83-22" title="22"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> by, <span class="dt">y =</span> growth)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-23" title="23"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-24" title="24"><span class="st"> </span><span class="kw">transition_time</span>(year) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-25" title="25"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year: {frame_time}&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-26" title="26"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Year of birth&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb83-27" title="27"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Salary increase (%)&quot;</span>)   </a>
<a class="sourceLine" id="cb83-28" title="28"><span class="kw">anim_save</span>(<span class="st">&quot;indGrowth2000-2013.gif&quot;</span>, <span class="dt">width =</span> <span class="dv">1000</span>, <span class="dt">height =</span> <span class="dv">1000</span>)  </a></code></pre></div>
<p><img src="https://mikaellundqvist.github.io/SCB-Engineers-Jonkoping/SCB-Engineers-Jonkoping_files/figure-html/indGrowth2000-2013.gif" /></p>
<p>Average monthly pay (total pay), non-manual workers private sector (SLP),<br />
SEK by occuptional (SSYK 2012), age, sex and year 2000-2013<br />
214 Engineering professionals<br />
sex=total<br />
Changes in the salary structure part by birthyear, salary structure part is<br />
defined as the derivative of the age / salary function, salary structure<br />
part defines how much the salaries needs to increase each year so that the<br />
structure remains unchanged.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">csvfile &lt;-<span class="st"> </span><span class="kw">readfile</span>(<span class="st">&quot;AM0103A9.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb84-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-4" title="4"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">age3 =</span> <span class="kw">unlist</span>(<span class="kw">lapply</span>(<span class="kw">strsplit</span>(<span class="kw">substr</span>(age, <span class="dv">1</span>, <span class="dv">5</span>), <span class="st">&quot;-&quot;</span>), strtoi))[<span class="dv">2</span>])    </a>
<a class="sourceLine" id="cb84-5" title="5">salaryStructure =<span class="st"> </span><span class="kw">data.frame</span>()  </a>
<a class="sourceLine" id="cb84-6" title="6"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">min</span>(csvfile<span class="op">$</span>year2)<span class="op">:</span><span class="kw">max</span>(csvfile<span class="op">$</span>year2)){  </a>
<a class="sourceLine" id="cb84-7" title="7">  yearfile &lt;-<span class="st"> </span><span class="kw">filter</span>(csvfile, year2 <span class="op">==</span><span class="st"> </span>i)  </a>
<a class="sourceLine" id="cb84-8" title="8">  x =<span class="st"> </span>yearfile<span class="op">$</span>year2 <span class="op">-</span><span class="st"> </span>(yearfile<span class="op">$</span>age2 <span class="op">+</span><span class="st"> </span>yearfile<span class="op">$</span>age3) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>  </a>
<a class="sourceLine" id="cb84-9" title="9">  model =<span class="st"> </span><span class="kw">lm</span>(yearfile<span class="op">$</span>salary <span class="op">~</span><span class="st"> </span>splines<span class="op">::</span><span class="kw">bs</span>(x, <span class="dv">8</span>))  </a>
<a class="sourceLine" id="cb84-10" title="10">  X =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span> <span class="kw">unlist</span>(<span class="kw">map2</span>( i <span class="op">-</span><span class="st"> </span><span class="dv">62</span>, i <span class="op">-</span><span class="st"> </span><span class="dv">22</span>, seq, <span class="dt">length =</span> <span class="dv">100</span>)))  </a>
<a class="sourceLine" id="cb84-11" title="11">  Y =<span class="st"> </span><span class="kw">predict</span>(model, X)   </a>
<a class="sourceLine" id="cb84-12" title="12">  dX =<span class="st"> </span><span class="kw">rowMeans</span>(<span class="kw">embed</span>(X<span class="op">$</span>x, <span class="dv">2</span>))  </a>
<a class="sourceLine" id="cb84-13" title="13">  dY =<span class="st"> </span><span class="op">-</span><span class="kw">diff</span>(Y) <span class="op">/</span><span class="st"> </span><span class="kw">diff</span>(X<span class="op">$</span>x) <span class="op">/</span><span class="st"> </span>Y  </a>
<a class="sourceLine" id="cb84-14" title="14">  temp &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(<span class="dt">year =</span> i, <span class="dt">dX =</span> dX, <span class="dt">dY =</span> dY))  </a>
<a class="sourceLine" id="cb84-15" title="15">  salaryStructure &lt;-<span class="st"> </span><span class="kw">rbind</span>(salaryStructure, temp)  </a>
<a class="sourceLine" id="cb84-16" title="16">}   </a>
<a class="sourceLine" id="cb84-17" title="17">salaryStructure <span class="op">%&gt;%</span><span class="st">   </span></a>
<a class="sourceLine" id="cb84-18" title="18"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> dX, <span class="dt">y =</span> dY)) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-19" title="19"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-20" title="20"><span class="st">  </span><span class="kw">transition_time</span>(year) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-21" title="21"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year: {frame_time}&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-22" title="22"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Year of birth&quot;</span>) <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb84-23" title="23"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Structural increase (%)&quot;</span>)   </a>
<a class="sourceLine" id="cb84-24" title="24"><span class="kw">anim_save</span>(<span class="st">&quot;salaryStructure2000-2013.gif&quot;</span>, <span class="dt">width =</span> <span class="dv">1000</span>, <span class="dt">height =</span> <span class="dv">1000</span>)  </a></code></pre></div>
<p><img src="https://mikaellundqvist.github.io/SCB-Engineers-Jonkoping/SCB-Engineers-Jonkoping_files/figure-html/salaryStructure2000-2013.gif" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="civilingenjorsutbildning-sun-2000.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ssyk-311.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SCB-Engineers-Jonkoping.pdf", "SCB-Engineers-Jonkoping.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
